import logging
import sys
import traceback
from collections.abc import Sequence
from dataclasses import dataclass
from typing import cast, override

import eleanor.variable_space as vs
from eleanor.exceptions import EleanorError
from eleanor.order import Order
from eleanor.output.interface import (
    AbstractOutputSink,
    ComputeResult,
    ErrorInfo,
    WriteOutcome,
    require_int_order_id,
)
from eleanor.output.postgres.persistence import connection as connection_module
from eleanor.output.postgres.persistence import repositories
from eleanor.output.postgres.settings import PostgresSinkSettings
from eleanor.progress import ProgressHandle

_PSYCOPG_LOGGER_NAME = "psycopg"


@dataclass(slots=True, frozen=True)
class PostgresPrepared:
    """One VS point's worth of work, as handed from prepare to commit.

    Currently the identity: the point graph itself, alongside the compute
    error that :meth:`PostgresSink.commit_batch` records against it. That
    costs nothing in the default configuration, where
    :meth:`PostgresSink.supports_worker_commit` is ``True`` and so both halves
    run in the same worker and the payload never crosses a process boundary.

    It *does* matter when a caller forces this sink down the serial path, where
    the graph is pickled back to the parent. Reducing it to a columnar payload
    -- one array per column per table, with the FK columns left for commit to
    stamp -- is a follow-on change confined to this module and
    :mod:`eleanor.output.postgres.persistence.repositories`. See
    :class:`AbstractOutputSink` for why columnar and not row-oriented.
    """

    point: vs.Point
    error: ErrorInfo | None


class PostgresSink(AbstractOutputSink[int]):
    """Persist Eleanor compute results into PostgreSQL via psycopg3.

    ``bulk_load_optimization`` (default ``False``) opts the sink in to
    a lifecycle-bracketed bulk-load window: :meth:`initialize` calls
    :func:`repositories.drop_bulk_load_objects` after the schema is in place, and
    :meth:`finalize` calls :func:`repositories.recreate_bulk_load_objects` just
    before the connection is closed. The constraints / indexes declared
    on the schema are therefore absent for the lifetime of the sink,
    which makes the per-row INSERT / COPY hot path substantially faster
    on large workloads. If the sink crashes between ``initialize`` and
    ``finalize`` -- e.g. the process is killed -- the constraints stay
    missing; ``eleanor postgres bulkload recreate`` (or :func:`recreate_bulk_load_objects`
    directly) will reattach them.
    """

    settings: PostgresSinkSettings
    _prev_psycopg_log_level: int | None
    _acquired: bool

    def __init__(self, settings: PostgresSinkSettings) -> None:
        self.settings = settings
        self._prev_psycopg_log_level = None
        self._acquired = False

    @override
    def initialize(self) -> None:
        """Open the connection and ensure the schema. Runs once per sink instance.

        Per the lifecycle docstring on :class:`OutputSink`, this is the
        eager moment for connection / schema setup: we want bad
        credentials, network problems, or schema mismatch to surface
        before any work has been queued.
        """
        if not self._acquired:
            connection_module.acquire(self.settings.database)
            self._acquired = True

        if self.settings.verbose:
            logger = logging.getLogger(_PSYCOPG_LOGGER_NAME)
            if self._prev_psycopg_log_level is None:
                self._prev_psycopg_log_level = logger.level
            logger.setLevel(logging.DEBUG)

        repositories.apply_pending_migrations(self.settings.database)
        if self.settings.bulk_load_optimization:
            repositories.drop_bulk_load_objects(self.settings.database)

    @override
    def begin_run(self, order: Order, *, requested_id: str | None = None) -> int:
        """Insert a new ``orders`` row, or resume the one ``requested_id`` names.

        The id space is the ``orders.id`` identity sequence, so a fresh run
        takes whatever the database assigns. A ``requested_id`` naming no
        existing row is an error: previously it was quietly inserted as a new
        order under a *different*, sequence-assigned id, which silently
        discarded the caller's request to extend.
        """
        if requested_id is None:
            return repositories.insert_order(self.settings.database, order).id

        order_id = require_int_order_id(requested_id, "postgres sink")
        existing = repositories.get_order(self.settings.database, order_id)
        if existing is None:
            msg = f"postgres sink has no order {order_id} to extend"
            raise EleanorError(msg)
        if order.eleanor_version != existing.eleanor_version:
            msg = "cannot extend an order generated by a different version of Eleanor"
            raise EleanorError(msg)

        return order_id

    @override
    def prepare_batch(self, order_id: int, results: Sequence[ComputeResult]) -> Sequence[PostgresPrepared]:
        """Pair each point with the compute error :meth:`commit_batch` records against it.

        ``order_id`` is unused here. The ``variable_space.order_id`` foreign key
        is stamped during the commit, where ``repositories.insert_point``
        receives the id as its own parameter, so the point graph never has to
        carry it.
        """
        _ = order_id
        return [PostgresPrepared(point=result.point, error=result.error) for result in results]

    @override
    def commit_batch(
        self,
        order_id: int,
        prepared: Sequence[object],
        progress: ProgressHandle | None = None,
    ) -> list[WriteOutcome]:
        """Persist a prepared batch.

        One outer transaction over the whole batch (so all surviving rows
        commit with a single fsync); each VS point lives inside its own
        ``savepoint`` so a single bad row can roll back without poisoning
        the rest. Successful outcomes are upgraded to ``committed=True``
        only after the outer commit lands, and the progress bar is ticked
        once per durably-written row.
        """
        outcomes: list[WriteOutcome] = []
        pending_slots: list[int] = []
        pending_results: list[int] = []

        conn = connection_module.connect(self.settings.database)
        try:
            with conn.transaction():
                for index, item in enumerate(cast("Sequence[PostgresPrepared]", prepared)):
                    point = item.point
                    try:
                        with conn.transaction(savepoint_name=f"vs_point_{index}"):
                            _ = repositories.insert_point(conn, order_id, point, item.error, self.settings)
                        pending_slots.append(len(outcomes))
                        pending_results.append(point.exit_code)
                        outcomes.append(
                            WriteOutcome(
                                exit_code=-1,
                                committed=False,
                            ),
                        )
                    except Exception as e:
                        message = (
                            f"PostgresSink.commit_batch: VS point index {index} "
                            f"failed and was rolled back: {type(e).__name__}: {e}"
                        )
                        print(message, file=sys.stderr)
                        traceback.print_exc(file=sys.stderr)
                        outcomes.append(
                            WriteOutcome(
                                exit_code=-1,
                                committed=False,
                                error_message=str(e),
                            ),
                        )
        except Exception as e:
            err = str(e)
            for slot in pending_slots:
                outcomes[slot] = WriteOutcome(
                    exit_code=-1,
                    committed=False,
                    error_message=err,
                )
            return outcomes

        for slot, exit_code in zip(pending_slots, pending_results, strict=True):
            outcomes[slot] = WriteOutcome(
                exit_code=exit_code,
                committed=True,
            )
            if progress is not None:
                progress.tick()
        return outcomes

    @override
    def finalize_run(self) -> None:
        """Per-run cleanup. Currently a no-op; reserved for the bulk-load follow-up."""
        return

    @override
    def finalize(self) -> None:
        """Release the persistent connection on sink shutdown.

        When ``bulk_load_optimization`` is enabled, reattach the
        constraints + indexes stripped in :meth:`initialize` *before*
        the connection is released (recreate uses the same connection
        cache). The recreate runs inside a :keyword:`try` whose
        :keyword:`finally` always releases, so a recreate failure
        (typically because the bulk-loaded data violates a constraint)
        leaves the database with constraints missing and propagates the
        exception, but never leaks the libpq socket.

        The release goes through
        :func:`~eleanor.output.postgres.persistence.connection.release`
        rather than closing outright: the connection cache is keyed on the
        database settings, so a second sink pointed at the same database
        shares these connections and must not have them closed under it.
        The last sink to release is the one that actually closes.
        """
        try:
            if self.settings.bulk_load_optimization:
                repositories.recreate_bulk_load_objects(self.settings.database)
        finally:
            connection_module.release(self.settings.database)
            self._acquired = False
            if self._prev_psycopg_log_level is not None:
                logging.getLogger(_PSYCOPG_LOGGER_NAME).setLevel(
                    self._prev_psycopg_log_level,
                )
                self._prev_psycopg_log_level = None

    @override
    def target_key(self) -> object:
        """The database, so a second sink cannot recreate indexes mid-bulk-load."""
        return self.settings.database

    @override
    def supports_worker_commit(self) -> bool:
        return True

    @override
    def supports_background_commit(self) -> bool:
        return False

    @override
    def supports_progress(self) -> bool:
        return True


__all__ = ["PostgresPrepared", "PostgresSink"]
