"""Unit tests for the rewritten persistence layer.

These tests run entirely in-memory: no DB connection is opened. They
cover three kinds of correctness checks the rewrite needs:

* DDL emission for every :data:`schema.TABLES` entry produces a valid
  ``CREATE TABLE`` string with the expected column / FK / check shape.
* Forward converters (``*_to_row``) emit dicts whose keys exactly
  match the non-identity columns of the corresponding table.
* Reverse converters (``row_to_*``) round-trip with the forward
  converters where applicable (``OrderRecord``, ``ScratchEntry``,
  kernel config).

Wire-level behaviour against a real Postgres lives in
``test/integration/output/test_postgres_sink.py``, gated on the
``ELEANOR_TEST_DATABASE_URL`` environment variable.
"""

import os
from contextlib import nullcontext
from datetime import datetime
from unittest import TestCase, mock

import numpy as np
from eleanor.config.kernel import KernelConfig
from eleanor.exceptions import EleanorException
from eleanor.kernel.eq36.settings import IOPG_1, Eq3Settings, Eq6Settings, Eq36Settings
from eleanor.order import Order
from eleanor.output.postgres.persistence import (
    connection,
    converters,
    queries,
    repositories,
    schema,
)
from eleanor.output.postgres.settings import PostgresDatabaseSettings
from eleanor.parameters import Parameter
from eleanor.reactants import ReactantType


def _mock_order() -> Order:
    return Order(
        name="name",
        notes="notes",
        creator="creator",
        kernel=mock.MagicMock(),
        temperature=Parameter.load(200.0),
        pressure=Parameter.load(100.0),
        elements={
            "C": Parameter.load(-6),
        },
    )


class TestSchemaDdlEmission(TestCase):
    """
    DDL emitted by :func:`schema.to_create_table_sql` covers every table
    and matches the structure declared in :data:`schema.TABLES`.
    """

    def test_every_table_emits_create_table_sql(self) -> None:
        """
        Ensure :func:`schema.to_create_table_sql` produces a non-empty
        ``CREATE TABLE IF NOT EXISTS`` statement for every declared table.
        """
        for table in schema.TABLES:
            sql = schema.to_create_table_sql(table)
            self.assertIn("CREATE TABLE IF NOT EXISTS", sql)
            self.assertIn(table.name, sql)
            for col in table.columns:
                self.assertIn(
                    col.name, sql, f"column {col.name} missing in {table.name} DDL"
                )

    def test_orders_ddl_includes_primary_key_and_indexes(self) -> None:
        """
        Ensure the orders table emits a primary key clause and every declared
        index gets its own ``CREATE INDEX`` statement. Identifiers are
        double-quoted so mixed-case names elsewhere in the schema survive
        Postgres' default folding.
        """
        ddl = schema.to_create_table_sql(schema.ORDERS)
        self.assertIn('PRIMARY KEY ("id")', ddl)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", ddl)
        for idx in schema.ORDERS.indexes:
            idx_sql = schema.to_create_index_sql(schema.ORDERS, idx)
            self.assertIn("CREATE INDEX IF NOT EXISTS", idx_sql)
            self.assertIn(f'"{idx.name}"', idx_sql)

    def test_variable_space_ddl_emits_foreign_key(self) -> None:
        """
        Ensure FK clauses (with ON DELETE CASCADE) land in the DDL for tables
        that declare a parent. Identifiers are double-quoted.
        """
        ddl = schema.to_create_table_sql(schema.VARIABLE_SPACE)
        self.assertIn('FOREIGN KEY ("order_id")', ddl)
        self.assertIn('REFERENCES "orders"("id")', ddl)
        self.assertIn("ON DELETE CASCADE", ddl)

    def test_suppressions_ddl_emits_check_constraint(self) -> None:
        """
        Ensure the suppressions ``CHECK`` constraint is rendered with its name.
        The constraint name is double-quoted alongside other identifiers.
        """
        ddl = schema.to_create_table_sql(schema.SUPPRESSIONS)
        self.assertIn('CONSTRAINT "suppressions_well_defined"', ddl)
        self.assertIn("name is not null or type is not null", ddl)

    def test_mixed_case_columns_are_quoted_in_ddl(self) -> None:
        """
        Ensure mixed-case columns like ``pH`` / ``Eh`` / ``log_fO2`` survive
        DDL emission as quoted identifiers. Without quoting, Postgres folds
        them to ``ph`` / ``eh`` / ``log_fo2`` and subsequent INSERTs (which
        do quote via :class:`psycopg.sql.Identifier`) fail with
        ``UndefinedColumn``.
        """
        ddl = schema.to_create_table_sql(schema.EQUILIBRIUM_SPACE)
        for case_sensitive in ("pH", "log_fO2", "Eh"):
            self.assertIn(f'"{case_sensitive}"', ddl)

    def test_pure_solids_ddl_emits_neg_inf_default(self) -> None:
        """
        Ensure the saturation-state ``log_*`` columns carry their ``-Infinity``
        default in the DDL output, matching the schema-level default the
        rewritten sink relies on as a safety net.
        """
        ddl = schema.to_create_table_sql(schema.EQUILIBRIUM_PURE_SOLIDS)
        self.assertIn("DEFAULT '-Infinity'::double precision", ddl)

    def test_to_drop_index_sql_emits_quoted_drop_if_exists(self) -> None:
        """
        Ensure :func:`schema.to_drop_index_sql` is the
        bulk-load-lifecycle counterpart of :func:`to_create_index_sql`,
        with ``IF EXISTS`` semantics and the index name double-quoted to
        survive Postgres' default identifier folding.
        """
        idx = schema.IndexDef(name="orders_name_idx", columns=("name",))
        self.assertEqual(
            schema.to_drop_index_sql(idx),
            'DROP INDEX IF EXISTS "orders_name_idx"',
        )

    def test_to_drop_constraint_sql_emits_quoted_alter_if_exists(self) -> None:
        """
        Ensure :func:`schema.to_drop_constraint_sql` produces an
        ``ALTER TABLE ... DROP CONSTRAINT IF EXISTS`` with both the
        table and the constraint name double-quoted. ``IF EXISTS``
        keeps the helper idempotent for fresh databases that have not
        yet had the constraint added.
        """
        self.assertEqual(
            schema.to_drop_constraint_sql(
                "variable_space", "variable_space_order_id_fkey"
            ),
            'ALTER TABLE "variable_space" DROP CONSTRAINT IF EXISTS "variable_space_order_id_fkey"',
        )

    def test_to_add_foreign_key_sql_uses_pg_default_name_and_preserves_on_delete(
        self,
    ) -> None:
        """
        Ensure :func:`schema.to_add_foreign_key_sql` emits an
        ``ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY ... ON DELETE``
        statement whose constraint name matches PG's own
        ``<table>_<column>_fkey`` convention -- so a recreated FK is
        indistinguishable from the inline-declared one -- and whose
        ``ON DELETE`` semantics are preserved verbatim from the
        :class:`ForeignKeyDef`.
        """
        ddl = schema.to_add_foreign_key_sql(
            schema.VARIABLE_SPACE,
            schema.ForeignKeyDef(column="order_id", references_table="orders"),
        )
        self.assertIn('ALTER TABLE "variable_space"', ddl)
        self.assertIn('ADD CONSTRAINT "variable_space_order_id_fkey"', ddl)
        self.assertIn('FOREIGN KEY ("order_id")', ddl)
        self.assertIn('REFERENCES "orders"("id")', ddl)
        self.assertIn("ON DELETE CASCADE", ddl)

    def test_to_add_foreign_key_sql_truncates_long_names_to_pg_limit(self) -> None:
        """
        Ensure :func:`schema._fk_constraint_name` (and therefore the DDL
        emitted by :func:`to_add_foreign_key_sql`) is capped at PG's
        ``NAMEDATALEN - 1`` identifier limit. Without truncation the
        server would silently shorten the name and our subsequent drops
        / recreates would refer to a name that doesn't exist on the wire.
        """
        long_table = "a_very_very_very_very_very_long_table_name_for_testing"
        long_column = "an_equally_long_column_name_to_make_things_overflow"
        full = f"{long_table}_{long_column}_fkey"
        self.assertGreater(len(full), 63)
        self.assertEqual(
            len(schema._fk_constraint_name(long_table, long_column)),
            63,
        )

    def test_to_add_check_sql_uses_declared_name_and_expression(self) -> None:
        """
        Ensure :func:`schema.to_add_check_sql` emits the same
        ``CONSTRAINT <name> CHECK (<expression>)`` shape as the
        table-level DDL, just promoted into an
        ``ALTER TABLE ... ADD CONSTRAINT`` statement.
        """
        ddl = schema.to_add_check_sql(
            schema.SUPPRESSIONS,
            schema.CheckDef(
                "suppressions_well_defined", "name is not null or type is not null"
            ),
        )
        self.assertIn('ALTER TABLE "suppressions"', ddl)
        self.assertIn('ADD CONSTRAINT "suppressions_well_defined"', ddl)
        self.assertIn("CHECK (name is not null or type is not null)", ddl)


class TestConverterShapes(TestCase):
    """
    Forward converters produce dicts whose keys exactly match the
    non-identity columns the corresponding table declares.
    """

    def _expected_keys(self, table: schema.TableDef) -> set[str]:
        return {c.name for c in table.columns if not c.identity}

    def test_kernel_to_row_shape(self) -> None:
        """
        Ensure :func:`converters.kernel_to_row` populates the expected key set
        (``id`` doubles as the FK in this table, so it is included).
        """
        kernel = KernelConfig(
            kind="eq36",
            settings=Eq36Settings(
                timeout=None,
                model=IOPG_1.B_DOT,
                charge_balance="Cl-",
                eq3_config=Eq3Settings(),
                eq6_config=Eq6Settings(),
            ),
        )
        row = converters.kernel_to_row(kernel, variable_space_id=7)
        self.assertEqual(set(row.keys()), self._expected_keys(schema.KERNEL))
        self.assertEqual(row["id"], 7)
        self.assertEqual(row["type"], "eq36")

    def test_es_point_to_row_covers_every_equilibrium_space_column(self) -> None:
        """
        Ensure :func:`converters.es_point_to_row` populates every non-identity
        column declared on ``equilibrium_space`` -- the row dict's keys are
        the contract bulk INSERTs depend on.
        """
        import eleanor.equilibrium_space as core_es

        point = core_es.Point(
            stage="eq3",
            temperature=np.float64(25.0),
            pressure=np.float64(1.0),
            pH=np.float64(7.0),
            log_fO2=-np.float64(60.0),
            Eh=np.float64(0.1),
            log_activity_water=-np.float64(0.01),
            log_ionic_strength=-np.float64(2.0),
            solute_mass=np.float64(0.1),
            solvent_mass=np.float64(1.0),
            solution_mass=np.float64(1.1),
            tds=np.float64(100.0),
            elements=[],
            aqueous_species=[],
            pure_solids=[],
            solid_solutions=[],
            gases=[],
            redox_reactions=[],
            custom_properties={
                "mole_fraction_water": np.float64(0.98),
                "log_gamma_water": np.float64(0.02),
                "pe": np.float64(4.0),
                "Ah": np.float64(1.2),
                "log_stoichiometric_ionic_strength": -np.float64(1.8),
                "ionic_asymmetry": np.float64(0.006),
                "stoichiometric_ionic_asymmetry": np.float64(0.007),
                "osmotic_coefficient": np.float64(0.8),
                "stoichiometric_osmotic_coefficient": np.float64(0.81),
                "log_sum_molalities": -np.float64(1.0),
                "log_sum_stoichiometric_molalities": -np.float64(0.9),
                "charge_imbalance": np.float64(0.0),
                "solute_fraction": np.float64(0.1),
                "solvent_fraction": np.float64(0.9),
            },
        )
        row = converters.es_point_to_row(point, variable_space_id=42)
        self.assertEqual(set(row.keys()), self._expected_keys(schema.EQUILIBRIUM_SPACE))
        self.assertEqual(row["variable_space_id"], 42)

    def test_es_pure_solid_to_row_replaces_none_with_neg_inf(self) -> None:
        """
        Ensure :func:`converters.es_pure_solid_to_row` substitutes
        ``-math.inf`` for ``None`` on the saturation-state columns (matches
        the schema's NOT NULL + ``-Infinity`` default).
        """
        import math

        import eleanor.equilibrium_space as core_es

        solid = core_es.PureSolid(
            name="Calcite",
            log_qk=np.float64(0.2),
            affinity=np.float64(1.0),
            # log_moles / log_mass / log_volume left at their None defaults.
        )
        row = converters.es_pure_solid_to_row(solid, equilibrium_space_id=5)
        self.assertEqual(row["log_moles"], -math.inf)
        self.assertEqual(row["log_mass"], -math.inf)
        self.assertEqual(row["log_volume"], -math.inf)

    def test_kernel_round_trip_via_converters(self) -> None:
        """
        Ensure :func:`converters.row_to_kernel_config` rehydrates a
        ``KernelConfig`` whose ``type`` matches the source after a
        forward+reverse converter round-trip.
        """
        kernel = KernelConfig(
            kind="eq36",
            settings=Eq36Settings(
                timeout=None,
                model=IOPG_1.B_DOT,
                charge_balance="Cl-",
                eq3_config=Eq3Settings(),
                eq6_config=Eq6Settings(),
            ),
        )
        forward = converters.kernel_to_row(kernel, variable_space_id=99)
        # Drop the Jsonb wrapper to mimic what psycopg returns on read.
        settings_obj = getattr(forward["settings"], "obj")
        round_trip_row = {
            "id": forward["id"],
            "type": forward["type"],
            "settings": settings_obj,
        }
        restored = converters.row_to_kernel_config(round_trip_row)
        self.assertEqual(restored.kind, "eq36")
        self.assertIsInstance(restored.settings, Eq36Settings)
        if not isinstance(restored.settings, Eq36Settings):
            raise AssertionError("expected Eq36Settings")
        self.assertEqual(restored.settings.charge_balance, "Cl-")

    def test_scratch_entry_shape(self) -> None:
        """
        Ensure :func:`converters.row_to_scratch_entry` projects a
        ``scratch`` row joined with its parent into the right dataclass.
        """
        entry = converters.row_to_scratch_entry(
            {
                "variable_space_id": 11,
                "exit_code": 0,
                "zip": b"compressed-bytes",
            }
        )
        self.assertEqual(entry.variable_space_id, 11)
        self.assertEqual(entry.exit_code, 0)
        self.assertEqual(entry.zip, b"compressed-bytes")


class TestOrderRecordRoundTrip(TestCase):
    """
    OrderRecord forward/reverse converters round-trip the identifying
    metadata used by ``PostgresSink.begin_run``.
    """

    def test_row_to_order_record_reconstructs_fields(self) -> None:
        """
        Ensure :func:`converters.row_to_order_record` projects a row dict
        into the right ``OrderRecord`` shape.
        """
        row: dict[str, object] = {
            "id": 7,
            "name": "demo",
            "tags": ["foo", "bar"],
            "eleanor_version": "v1",
            "raw": {"k": "v"},
            "create_date": datetime(2026, 1, 1, 0, 0, 0),
        }
        record = converters.row_to_order_record(row)
        self.assertEqual(record.id, 7)
        self.assertEqual(record.name, "demo")
        self.assertEqual(record.tags, ["foo", "bar"])
        self.assertEqual(record.eleanor_version, "v1")
        self.assertEqual(record.raw, {"k": "v"})

    def test_row_to_order_record_empty_tags(self) -> None:
        """
        Ensure :func:`converters.row_to_order_record` correctly handles an empty tags list.
        """
        row: dict[str, object] = {
            "id": 1,
            "name": "demo",
            "tags": [],
            "eleanor_version": "v1",
            "raw": {},
            "create_date": datetime(2026, 1, 1, 0, 0, 0),
        }
        record = converters.row_to_order_record(row)
        self.assertEqual(record.tags, [])


class _FakeCopy(object):
    """Tiny COPY context manager capturing rows handed to ``write_row``."""

    rows: list[tuple[object, ...]]
    types: list[int | str]

    def __init__(self) -> None:
        self.rows = []
        self.types = []

    def __enter__(self) -> "_FakeCopy":
        return self

    def __exit__(
        self,
        _exc_type: type[BaseException] | None,
        _exc: BaseException | None,
        _tb: object,
    ) -> None:
        return None

    def set_types(self, types: list[int | str]) -> None:
        self.types = list(types)

    def write_row(self, row: tuple[object, ...]) -> None:
        self.rows.append(row)


class TestBulkInsertHelpers(TestCase):
    """Internal bulk helpers chunk oversized INSERTs and COPY large leaf batches."""

    def test_bulk_insert_returning_ids_chunks_large_batches_and_preserves_order(
        self,
    ) -> None:
        """Ensure oversized RETURNING batches split into multiple execute calls."""
        cursor = mock.MagicMock()
        cursor.fetchall.side_effect = [[(11,), (12,)], [(13,), (14,)], [(15,)]]
        rows: list[dict[str, object]] = [
            {"a": 1, "b": 10, "c": 100},
            {"a": 2, "b": 20, "c": 200},
            {"a": 3, "b": 30, "c": 300},
            {"a": 4, "b": 40, "c": 400},
            {"a": 5, "b": 50, "c": 500},
        ]
        with mock.patch.object(repositories, "_MAX_BIND_PARAMS_PER_STATEMENT", 6):
            ids = repositories._bulk_insert_returning_ids(
                cursor,
                "equilibrium_space",
                rows,
            )

        self.assertEqual(ids, [11, 12, 13, 14, 15])
        self.assertEqual(cursor.execute.call_count, 3)
        flat_lengths = [len(call.args[1]) for call in cursor.execute.call_args_list]
        self.assertEqual(flat_lengths, [6, 6, 3])

    def test_bulk_insert_uses_copy_above_threshold(self) -> None:
        """Ensure large fire-and-forget batches route through COPY."""
        cursor = mock.MagicMock()
        rows: list[dict[str, object]] = [
            {"a": 1},
            {"a": 2},
            {"a": 3},
        ]
        with (
            mock.patch.object(repositories, "_COPY_ROW_THRESHOLD", 3),
            mock.patch.object(repositories, "_bulk_copy") as bulk_copy,
        ):
            repositories._bulk_insert(
                cursor,
                "equilibrium_elements",
                rows,
            )

        bulk_copy.assert_called_once_with(cursor, "equilibrium_elements", rows)
        cursor.executemany.assert_not_called()

    def test_bulk_insert_uses_executemany_below_threshold(self) -> None:
        """Ensure small fire-and-forget batches stay on ``executemany``."""
        cursor = mock.MagicMock()
        rows: list[dict[str, object]] = [
            {"a": 1},
            {"a": 2},
        ]
        with (
            mock.patch.object(repositories, "_COPY_ROW_THRESHOLD", 3),
            mock.patch.object(repositories, "_bulk_copy") as bulk_copy,
        ):
            repositories._bulk_insert(
                cursor,
                "equilibrium_elements",
                rows,
            )

        bulk_copy.assert_not_called()
        cursor.executemany.assert_called_once_with(
            queries.INSERTS["equilibrium_elements"],
            rows,
        )

    def test_bulk_copy_writes_rows_in_dict_key_order(self) -> None:
        """Ensure binary COPY receives tuple rows + per-column types in dict key order."""
        cursor = mock.MagicMock()
        fake_copy = _FakeCopy()
        cursor.copy.return_value = fake_copy
        rows: list[dict[str, object]] = [
            {
                "equilibrium_space_id": 7,
                "name": "Na",
                "log_molality": -1.0,
                "mass_fraction": 0.5,
            },
            {
                "equilibrium_space_id": 7,
                "name": "Cl",
                "log_molality": -1.2,
                "mass_fraction": 0.4,
            },
        ]

        repositories._bulk_copy(
            cursor,
            "equilibrium_elements",
            rows,
        )

        cursor.copy.assert_called_once()
        self.assertEqual(
            fake_copy.rows,
            [
                (7, "Na", -1.0, 0.5),
                (7, "Cl", -1.2, 0.4),
            ],
        )
        # Pinning column types is what keeps psycopg from inferring an
        # ``INTEGER`` column as ``int8`` at binary-copy time.
        self.assertEqual(
            fake_copy.types,
            ["int4", "text", "float8", "float8"],
        )

    def test_bulk_insert_returning_ids_is_noop_for_empty_rows(self) -> None:
        """
        Ensure ``_bulk_insert_returning_ids`` short-circuits before
        building any SQL when handed an empty rows list. Callers in
        ``_insert_es_subtree`` and ``_insert_vs_side_leaves`` rely on
        this so empty leaf collections don't emit no-op INSERTs.
        """
        cursor = mock.MagicMock()
        ids = repositories._bulk_insert_returning_ids(
            cursor,
            "equilibrium_space",
            [],
        )
        self.assertEqual(ids, [])
        cursor.execute.assert_not_called()
        cursor.fetchall.assert_not_called()

    def test_bulk_copy_is_noop_for_empty_rows(self) -> None:
        """
        Ensure ``_bulk_copy`` short-circuits when handed an empty rows
        list -- the ``cursor.copy()`` call is never opened, so we don't
        emit a stray ``COPY ... FROM STDIN`` to the wire.
        """
        cursor = mock.MagicMock()
        repositories._bulk_copy(
            cursor,
            "equilibrium_elements",
            [],
        )
        cursor.copy.assert_not_called()

    def test_bulk_insert_is_noop_for_empty_rows(self) -> None:
        """
        Ensure ``_bulk_insert`` short-circuits before reaching either
        the ``executemany`` or ``COPY`` branch when handed an empty
        rows list.
        """
        cursor = mock.MagicMock()
        repositories._bulk_insert(
            cursor,
            "equilibrium_elements",
            [],
        )
        cursor.executemany.assert_not_called()
        cursor.copy.assert_not_called()


class TestRepositoryErrorPaths(TestCase):
    """Defensive error branches in :mod:`repositories` that real PG can't easily induce."""

    def test_setup_schema_wires_connect_to_ensure_schema(self) -> None:
        """
        Ensure :func:`repositories.setup_schema` is just
        ``schema.ensure_schema(connection.connect(config))`` -- the
        public hook the sink's ``initialize`` calls. Mocked here so the
        unit suite covers the entry point even without a live DB.
        """
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        fake_conn = mock.MagicMock()
        with (
            mock.patch.object(connection, "connect", return_value=fake_conn) as connect,
            mock.patch.object(schema, "ensure_schema") as ensure_schema,
        ):
            repositories.setup_schema(cfg)
        connect.assert_called_once_with(cfg)
        ensure_schema.assert_called_once_with(fake_conn)

    def test_insert_order_raises_when_returning_clause_yields_no_row(self) -> None:
        """
        Ensure ``insert_order`` raises a clear ``EleanorException`` when
        the ``RETURNING id`` clause comes back empty -- the only way the
        sink is allowed to surface that situation. We can't induce this
        from real PG (a successful INSERT always RETURNS a row), so the
        only way to keep the defensive branch live is a unit test.
        """
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        order = _mock_order()
        fake_conn = mock.MagicMock()
        fake_conn.transaction.return_value = nullcontext()
        cursor = mock.MagicMock()
        cursor.fetchone.return_value = None
        fake_conn.cursor.return_value.__enter__.return_value = cursor
        with mock.patch.object(
            connection,
            "connect",
            return_value=fake_conn,
        ):
            with self.assertRaisesRegex(
                EleanorException, "order INSERT did not return an id"
            ):
                _ = repositories.insert_order(cfg, order)

    def test_get_order_returns_none_when_no_row_matches(self) -> None:
        """
        Ensure :func:`repositories.get_order` returns ``None`` rather
        than raising when the ``WHERE id = %s`` clause matches zero
        rows. ``begin_run`` relies on this to decide whether to insert.
        """
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        cursor = mock.MagicMock()
        cursor.fetchone.return_value = None
        fake_conn = mock.MagicMock()
        fake_conn.cursor.return_value.__enter__.return_value = cursor
        with mock.patch.object(
            connection,
            "connect",
            return_value=fake_conn,
        ):
            self.assertIsNone(repositories.get_order(cfg, 999))

    def test_insert_variable_space_raises_when_returning_yields_nothing(self) -> None:
        """
        Ensure :func:`_insert_variable_space_and_pair` raises an
        ``EleanorException`` when the ``variable_space`` INSERT's
        ``RETURNING`` clause comes back empty. Same defensive pattern
        as ``insert_order``; same unit-only coverage rationale.
        """
        cursor = mock.MagicMock()
        cursor.fetchone.return_value = None
        point = mock.MagicMock(
            water_mass=1.0,
            temperature=25.0,
            pressure=1.0,
            exit_code=0,
            create_date=datetime(2026, 1, 1),
            start_date=datetime(2026, 1, 1),
            complete_date=datetime(2026, 1, 1),
        )
        with self.assertRaisesRegex(
            EleanorException,
            "variable_space INSERT did not return an id",
        ):
            _ = repositories._insert_variable_space_and_pair(
                cursor,
                point,
                order_id=1,
            )


class TestConverterErrorAndReactantPaths(TestCase):
    """Converter error paths + the reactant-family converters not exercised elsewhere."""

    def test_normalize_dict_rejects_non_mapping_payloads(self) -> None:
        """
        Ensure :func:`normalize_dict` raises a clear
        :class:`EleanorException` (instead of letting psycopg's JSONB
        adapter fail later) when handed a non-dict value that's not a
        dataclass either.
        """
        with self.assertRaisesRegex(EleanorException, "must serialize to a dict"):
            _ = converters.normalize_dict(42, "order")

    def test_order_to_row_allows_missing_name(self) -> None:
        """
        Ensure :func:`order_to_row` leaves ``name`` enforcement to DB-level
        constraints and only performs the sink-required metadata checks.
        """
        order = _mock_order()
        order.name = None  # pyright: ignore[reportAttributeAccessIssue]

        row = converters.order_to_row(order)
        self.assertIn("name", row)
        self.assertIsNone(row["name"])

    def test_reactant_family_converters_emit_uniform_row_shape(self) -> None:
        """
        Ensure every reactant-family converter that shares the
        ``(name, log_moles, titration_rate)`` shape produces a row dict
        whose keys exactly match the corresponding table's non-identity
        columns. This is the contract every executemany / COPY caller
        relies on.
        """
        import eleanor.variable_space as core_vs

        cases = [
            (
                converters.mineral_reactant_to_row(
                    core_vs.MineralReactant(
                        name="m",
                        log_moles=np.float64(0.0),
                        titration_rate=np.float64(1.0),
                    ),
                    variable_space_id=7,
                ),
                schema.MINERAL_REACTANTS,
            ),
            (
                converters.aqueous_reactant_to_row(
                    core_vs.AqueousReactant(
                        name="a",
                        log_moles=np.float64(0.0),
                        titration_rate=np.float64(1.0),
                    ),
                    variable_space_id=7,
                ),
                schema.AQUEOUS_REACTANTS,
            ),
            (
                converters.gas_reactant_to_row(
                    core_vs.GasReactant(
                        name="g",
                        log_moles=np.float64(0.0),
                        titration_rate=np.float64(1.0),
                    ),
                    variable_space_id=7,
                ),
                schema.GAS_REACTANTS,
            ),
            (
                converters.element_reactant_to_row(
                    core_vs.ElementReactant(
                        name="e",
                        log_moles=np.float64(0.0),
                        titration_rate=np.float64(1.0),
                    ),
                    variable_space_id=7,
                ),
                schema.ELEMENT_REACTANTS,
            ),
            (
                converters.special_reactant_to_row(
                    core_vs.SpecialReactant(
                        name="s",
                        log_moles=np.float64(0.0),
                        titration_rate=np.float64(1.0),
                        composition=[],
                    ),
                    variable_space_id=7,
                ),
                schema.SPECIAL_REACTANTS,
            ),
            (
                converters.solid_solution_reactant_to_row(
                    core_vs.SolidSolutionReactant(
                        name="ss",
                        log_moles=np.float64(0.0),
                        titration_rate=np.float64(1.0),
                        end_members=[],
                    ),
                    variable_space_id=7,
                ),
                schema.SOLID_SOLUTION_REACTANTS,
            ),
        ]
        for row, table in cases:
            with self.subTest(table=table.name):
                expected = {c.name for c in table.columns if not c.identity}
                self.assertEqual(
                    set(row.keys()),
                    expected,
                    f"{table.name}: row keys {set(row.keys())} != expected {expected}",
                )
                self.assertEqual(row["variable_space_id"], 7)

    def test_special_reactant_composition_to_row_shape(self) -> None:
        """Ensure the special-reactant child composition row shape matches its table."""
        import eleanor.variable_space as core_vs

        row = converters.special_reactant_composition_to_row(
            core_vs.SpecialReactantComposition(element="Fe", count=1),
            special_reactant_id=11,
        )
        expected = {
            c.name
            for c in schema.SPECIAL_REACTANT_COMPOSITIONS.columns
            if not c.identity
        }
        self.assertEqual(set(row.keys()), expected)
        self.assertEqual(row["special_reactant_id"], 11)

    def test_fixed_gas_reactant_to_row_shape(self) -> None:
        """Ensure the fixed-gas reactant row shape includes ``log_fugacity`` instead of ``titration_rate``."""
        import eleanor.variable_space as core_vs

        row = converters.fixed_gas_reactant_to_row(
            core_vs.FixedGasReactant(
                name="O2(g)", log_moles=-np.float64(2.0), log_fugacity=-np.float64(2.0)
            ),
            variable_space_id=7,
        )
        expected = {
            c.name for c in schema.FIXED_GAS_REACTANTS.columns if not c.identity
        }
        self.assertEqual(set(row.keys()), expected)
        self.assertIn("log_fugacity", row)

    def test_es_reactant_to_row_shape(self) -> None:
        """Ensure the ES-side reactant row shape carries every kinetic field."""
        import eleanor.equilibrium_space as core_es

        row = converters.es_reactant_to_row(
            core_es.Reactant(
                name="forsterite",
                affinity=np.float64(1.0),
                relative_rate=np.float64(1.0),
                log_moles_reacted=-np.float64(2.0),
                log_moles_remaining=-np.float64(1.0),
                log_mass_reacted=-np.float64(2.0),
                log_mass_remaining=-np.float64(1.0),
            ),
            equilibrium_space_id=11,
        )
        expected = {
            c.name for c in schema.EQUILIBRIUM_REACTANTS.columns if not c.identity
        }
        self.assertEqual(set(row.keys()), expected)
        self.assertEqual(row["equilibrium_space_id"], 11)

    def test_normalize_dict_recurses_through_lists_and_enums(self) -> None:
        payload = {
            "reactants": [
                {"type": ReactantType.MINERAL, "log_moles": np.float64(-1.0)}
            ],
            "nested": {"v": [np.int64(2), {"x": np.float64(0.5)}]},
        }
        out = converters.normalize_dict(payload, "test")
        self.assertIsInstance(out["reactants"], list)
        assert isinstance(out["reactants"], list)
        self.assertEqual(out["reactants"][0]["type"], "mineral")
        self.assertIsInstance(out["reactants"][0]["log_moles"], float)
        self.assertEqual(out["nested"], {"v": [2, {"x": 0.5}]})


class TestConnectionCacheBehaviour(TestCase):
    """Process-local connection memoization paths in :mod:`connection`."""

    def test_connect_evicts_and_reopens_a_dead_cached_connection(self) -> None:
        """
        Ensure :func:`connection.connect` transparently replaces a
        cached connection that's been closed under us (server restart,
        network blip). The eviction must happen even though the cache
        entry is non-None, otherwise long-running workers wedge on the
        first reconnect.
        """
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        dead = mock.MagicMock()
        dead.closed = True
        fresh = mock.MagicMock()
        fresh.closed = False

        with (
            mock.patch.dict(
                connection._connections,
                {(cfg, os.getpid()): dead},
                clear=False,
            ),
            mock.patch.object(
                connection.psycopg,  # pyright: ignore[reportPrivateImportUsage]
                "connect",
                return_value=fresh,
            ) as connect,
            mock.patch.object(
                connection,
                "set_json_dumps",
            ) as set_json,
        ):
            got = connection.connect(cfg)

        self.assertIs(got, fresh)
        connect.assert_called_once()
        set_json.assert_called_once_with(connection._json_dumps, fresh)

    def test_close_all_connections_drains_cache_even_when_close_raises(self) -> None:
        """
        Ensure :func:`_close_all_connections` empties the process-local
        cache regardless of any :meth:`Connection.close` raising. The
        atexit hook must be best-effort -- partial cleanup is still
        better than leaving the interpreter holding live sockets.
        """
        cfg_a = PostgresDatabaseSettings(database="a", username="u", password="p")
        cfg_b = PostgresDatabaseSettings(database="b", username="u", password="p")
        broken = mock.MagicMock()
        broken.closed = False
        broken.close.side_effect = RuntimeError("close blew up")
        ok = mock.MagicMock()
        ok.closed = False

        # Replace the cache contents under control so we don't disturb
        # any real cached connections held by other tests.
        original = dict(connection._connections)
        connection._connections.clear()
        connection._connections[(cfg_a, os.getpid())] = broken
        connection._connections[(cfg_b, os.getpid())] = ok
        try:
            connection._close_all_connections()
        finally:
            connection._connections.update(original)

        # Both connections were drained from the cache (the cleanup
        # ran ``del`` on each one). The exception from ``broken``
        # was swallowed, and the surviving entry's ``close`` ran.
        self.assertEqual(len(connection._connections.keys()), 0)
        self.assertEqual(broken.close.call_count, 1)
        self.assertEqual(ok.close.call_count, 1)

    def test_close_all_connections_only_closes_locally_owned_connections(self) -> None:
        """
        Ensure :func:`_close_all_connections` only closes connections owned
        by the local process.
        """
        cfg_a = PostgresDatabaseSettings(database="a", username="u", password="p")
        cfg_b = PostgresDatabaseSettings(database="b", username="u", password="p")
        local = mock.MagicMock()
        local.closed = False
        local.close.side_effect = RuntimeError("close blew up")
        foreign = mock.MagicMock()
        foreign.closed = False

        # Replace the cache contents under control so we don't disturb
        # any real cached connections held by other tests.
        original = dict(connection._connections)
        connection._connections.clear()
        connection._connections[(cfg_a, os.getpid())] = local
        connection._connections[(cfg_b, os.getpid() + 1)] = foreign
        try:
            connection._close_all_connections()
        finally:
            connection._connections.update(original)

        # Only the local connection was drained from the cache (the
        # cleanup ran ``del`` on it). The exception from ``local``
        # was swallowed, and the surviving entry's ``close`` was not
        # called.
        self.assertEqual(len(connection._connections.keys()), 1)
        self.assertNotIn((cfg_a, os.getpid()), connection._connections)
        self.assertIn((cfg_b, os.getpid() + 1), connection._connections)
        self.assertEqual(local.close.call_count, 1)
        self.assertEqual(foreign.close.call_count, 0)


class TestBulkLoadLifecycle(TestCase):
    """Coverage of :func:`schema.drop_indexes` / :func:`schema.recreate_indexes` / :func:`schema.bulk_load_window`.

    These helpers issue DDL against a real Postgres in production; the
    unit suite mocks the cursor so we can pin down the
    statement-level contract without touching a live DB.
    """

    def _fake_conn_with_cursor(
        self,
        cursor: "mock.MagicMock | None" = None,
    ) -> "tuple[mock.MagicMock, mock.MagicMock]":
        """Build a fake connection whose ``transaction()`` and ``cursor()`` no-op.

        Returns ``(connection, cursor)``. ``connection.transaction`` and
        ``connection.cursor`` both expand to ``nullcontext()``-shaped
        managers so the tests can read whatever statements the body
        emits without psycopg machinery.
        """
        cur = cursor if cursor is not None else mock.MagicMock()
        conn = mock.MagicMock()
        conn.transaction.return_value = nullcontext()
        conn.cursor.return_value.__enter__.return_value = cur
        conn.cursor.return_value.__exit__.return_value = None
        return conn, cur

    @staticmethod
    def _executed_statements(cursor: mock.MagicMock) -> list[str]:
        """Return the literal SQL string passed to each ``cursor.execute`` call."""
        out: list[str] = []
        for call in cursor.execute.call_args_list:
            stmt = call.args[0]
            out.append(stmt if isinstance(stmt, str) else str(stmt))
        return out

    def test_drop_indexes_introspects_fks_and_drops_named_checks_and_indexes(
        self,
    ) -> None:
        """
        Ensure :func:`schema.drop_indexes` issues, for every declared
        table, an introspection query against ``information_schema``
        followed by ``ALTER TABLE ... DROP CONSTRAINT IF EXISTS`` for
        each FK name returned, ``ALTER TABLE ... DROP CONSTRAINT IF
        EXISTS`` for each declared CHECK, and ``DROP INDEX IF EXISTS``
        for each declared index. The introspection covers FKs created
        with PG's auto-naming so existing databases (with unnamed
            constraints) still get cleaned up.
        """
        cursor = mock.MagicMock()
        # Every introspection call returns a single fake FK name keyed
        # off the table being inspected, so we can verify the drop maps
        # 1:1.
        fk_calls_seen: list[str] = []

        def fake_execute(stmt: object, params: object = None) -> object:
            text = stmt if isinstance(stmt, str) else str(stmt)
            if "information_schema.table_constraints" in text and isinstance(
                params, tuple
            ):
                fk_calls_seen.append(params[1])  # the table name
            return cursor

        cursor.execute.side_effect = fake_execute
        cursor.fetchall.side_effect = (
            [(f"{table.name}_fk_synth",)] for table in schema.TABLES
        )
        conn, _ = self._fake_conn_with_cursor(cursor)

        schema.drop_indexes(conn)

        # Every declared table got an introspection query.
        self.assertEqual(
            fk_calls_seen,
            [t.name for t in schema.TABLES],
        )

        statements = self._executed_statements(cursor)
        # For each table, we expect one introspection query, then
        # whatever DROPs that table requires. The exact order doesn't
        # matter for correctness; what matters is the substrings.
        for table in schema.TABLES:
            self.assertTrue(
                any(
                    f'DROP CONSTRAINT IF EXISTS "{table.name}_fk_synth"' in s
                    for s in statements
                ),
                f"expected synthesized FK drop for table {table.name!r}",
            )
            for check in table.checks:
                self.assertTrue(
                    any(
                        f'DROP CONSTRAINT IF EXISTS "{check.name}"' in s
                        for s in statements
                    ),
                    f"expected CHECK drop for {check.name!r}",
                )
            for idx in table.indexes:
                self.assertTrue(
                    any(f'DROP INDEX IF EXISTS "{idx.name}"' in s for s in statements),
                    f"expected index drop for {idx.name!r}",
                )

    def test_drop_indexes_runs_inside_a_transaction(self) -> None:
        """
        Ensure :func:`schema.drop_indexes` opens a transaction so a
        partial drop never lands. Without the bracket, a mid-loop error
        would leave the database in a half-stripped state.
        """
        cursor = mock.MagicMock()
        cursor.fetchall.return_value = []
        conn, _ = self._fake_conn_with_cursor(cursor)

        schema.drop_indexes(conn)
        conn.transaction.assert_called_once_with()

    def test_recreate_indexes_emits_create_then_check_then_fk(self) -> None:
        """
        Ensure :func:`schema.recreate_indexes` emits, for every
        declared table, ``CREATE INDEX IF NOT EXISTS`` for each
        :class:`IndexDef`, ``ALTER TABLE ... ADD CONSTRAINT ... CHECK``
        for each :class:`CheckDef`, and ``ALTER TABLE ... ADD
        CONSTRAINT ... FOREIGN KEY`` for each :class:`ForeignKeyDef`.
        Within each table, the order is documented as indexes then
        CHECKs then FKs.
        """
        cursor = mock.MagicMock()
        conn, _ = self._fake_conn_with_cursor(cursor)

        schema.recreate_indexes(conn)

        statements = self._executed_statements(cursor)
        # Exactly one statement for every declared object.
        for table in schema.TABLES:
            for idx in table.indexes:
                self.assertTrue(
                    any(
                        f'CREATE INDEX IF NOT EXISTS "{idx.name}"' in s
                        for s in statements
                    ),
                    f"missing CREATE INDEX for {idx.name!r}",
                )
            for check in table.checks:
                self.assertTrue(
                    any(
                        f'ADD CONSTRAINT "{check.name}"' in s and "CHECK" in s
                        for s in statements
                    ),
                    f"missing ADD CHECK for {check.name!r}",
                )
            for fk in table.foreign_keys:
                fk_name = schema._fk_constraint_name(table.name, fk.column)
                self.assertTrue(
                    any(
                        f'ADD CONSTRAINT "{fk_name}"' in s and "FOREIGN KEY" in s
                        for s in statements
                    ),
                    f"missing ADD FK for {fk_name!r}",
                )

    def test_recreate_indexes_runs_inside_a_transaction(self) -> None:
        """Ensure the recreate also runs inside a single transaction."""
        cursor = mock.MagicMock()
        conn, _ = self._fake_conn_with_cursor(cursor)

        schema.recreate_indexes(conn)
        conn.transaction.assert_called_once_with()

    def test_bulk_load_window_drops_on_enter_and_recreates_on_exit(self) -> None:
        """
        Ensure :func:`schema.bulk_load_window` calls
        :func:`drop_indexes` before yielding and
        :func:`recreate_indexes` after the body returns -- the
        symmetric guard the docstring promises.
        """
        events: list[str] = []
        with (
            mock.patch.object(
                schema,
                "drop_indexes",
                side_effect=lambda _conn: events.append("drop"),
            ),
            mock.patch.object(
                schema,
                "recreate_indexes",
                side_effect=lambda _conn: events.append("recreate"),
            ),
        ):
            with schema.bulk_load_window(mock.MagicMock()):
                events.append("body")

        self.assertEqual(events, ["drop", "body", "recreate"])

    def test_bulk_load_window_recreates_even_when_body_raises(self) -> None:
        """
        Ensure the recreate phase runs in :keyword:`finally`, so a
        bulk-load that fails mid-flight still puts the constraints
        back. The original exception must propagate unchanged.
        """
        events: list[str] = []
        with (
            mock.patch.object(
                schema,
                "drop_indexes",
                side_effect=lambda _conn: events.append("drop"),
            ),
            mock.patch.object(
                schema,
                "recreate_indexes",
                side_effect=lambda _conn: events.append("recreate"),
            ),
        ):
            with self.assertRaisesRegex(RuntimeError, "mid-flight"):
                with schema.bulk_load_window(mock.MagicMock()):
                    events.append("body")
                    raise RuntimeError("mid-flight")

        self.assertEqual(events, ["drop", "body", "recreate"])

    def test_repositories_drop_indexes_wires_connect_to_schema(self) -> None:
        """
        Ensure :func:`repositories.drop_indexes` is just
        ``schema.drop_indexes(connection.connect(config))`` -- the
        :class:`PostgresDatabaseSettings`-keyed convenience the CLI uses.
        """
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        fake_conn = mock.MagicMock()
        with (
            mock.patch.object(
                connection,
                "connect",
                return_value=fake_conn,
            ) as connect,
            mock.patch.object(schema, "drop_indexes") as drop_indexes,
        ):
            repositories.drop_indexes(cfg)
        connect.assert_called_once_with(cfg)
        drop_indexes.assert_called_once_with(fake_conn)

    def test_repositories_recreate_indexes_wires_connect_to_schema(self) -> None:
        """Ensure the recreate wrapper is the same shape as the drop wrapper."""
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        fake_conn = mock.MagicMock()
        with (
            mock.patch.object(
                connection,
                "connect",
                return_value=fake_conn,
            ) as connect,
            mock.patch.object(schema, "recreate_indexes") as recreate_indexes,
        ):
            repositories.recreate_indexes(cfg)
        connect.assert_called_once_with(cfg)
        recreate_indexes.assert_called_once_with(fake_conn)

    def test_repositories_bulk_load_window_delegates_to_schema_window(self) -> None:
        """
        Ensure :func:`repositories.bulk_load_window` opens the
        process-local connection, delegates to
        :func:`schema.bulk_load_window`, and yields once. The body
        runs while the schema-level guard is held.
        """
        cfg = PostgresDatabaseSettings(database="db", username="u", password="p")
        fake_conn = mock.MagicMock()
        events: list[str] = []

        def fake_window(_conn):
            events.append("drop")
            try:
                yield
            finally:
                events.append("recreate")

        with (
            mock.patch.object(
                connection,
                "connect",
                return_value=fake_conn,
            ) as connect,
            mock.patch.object(
                schema,
                "bulk_load_window",
                side_effect=lambda c: __import__("contextlib").contextmanager(
                    fake_window
                )(c),
            ),
        ):
            with repositories.bulk_load_window(cfg):
                events.append("body")

        connect.assert_called_once_with(cfg)
        self.assertEqual(events, ["drop", "body", "recreate"])
