CREATE TABLE IF NOT EXISTS "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" TEXT NOT NULL,
  "tag" TEXT NOT NULL DEFAULT '',
  "eleanor_version" TEXT NOT NULL,
  "raw" JSONB NOT NULL,
  "create_date" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "variable_space" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "water_mass" DOUBLE PRECISION NOT NULL,
  "temperature" DOUBLE PRECISION NOT NULL,
  "pressure" DOUBLE PRECISION NOT NULL,
  "exit_code" INTEGER NOT NULL,
  "create_date" TIMESTAMP NOT NULL,
  "start_date" TIMESTAMP NOT NULL,
  "complete_date" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "kernel" (
  "id" INTEGER NOT NULL,
  "type" TEXT NOT NULL,
  "settings" JSONB NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "scratch" (
  "id" INTEGER NOT NULL,
  "zip" BYTEA NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "elements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_molality" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "species" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "value" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "suppressions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT,
  "type" TEXT,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE,
  CONSTRAINT "suppressions_well_defined" CHECK (name is not null or type is not null)
);

CREATE TABLE IF NOT EXISTS "suppression_exceptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" TEXT NOT NULL,
  "suppression_id" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("suppression_id") REFERENCES "suppressions"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "mineral_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "titration_rate" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "aqueous_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "titration_rate" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "gas_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "titration_rate" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "element_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "titration_rate" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "special_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "titration_rate" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "special_reactant_compositions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "special_reactant_id" INTEGER NOT NULL,
  "element" TEXT NOT NULL,
  "count" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("special_reactant_id") REFERENCES "special_reactants"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "fixed_gas_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "log_fugacity" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "solid_solution_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL,
  "titration_rate" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "solid_solution_reactant_end_members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "solid_solution_reactant_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "fraction" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("solid_solution_reactant_id") REFERENCES "solid_solution_reactants"("id") ON DELETE CASCADE,
  CONSTRAINT "fraction_in_range" CHECK (0.0 <= fraction AND fraction <= 1.0)
);

CREATE TABLE IF NOT EXISTS "equilibrium_space" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_space_id" INTEGER,
  "stage" TEXT NOT NULL,
  "log_xi" DOUBLE PRECISION,
  "temperature" DOUBLE PRECISION NOT NULL,
  "pressure" DOUBLE PRECISION NOT NULL,
  "pH" DOUBLE PRECISION NOT NULL,
  "log_fO2" DOUBLE PRECISION NOT NULL,
  "log_activity_water" DOUBLE PRECISION NOT NULL,
  "mole_fraction_water" DOUBLE PRECISION NOT NULL,
  "log_gamma_water" DOUBLE PRECISION NOT NULL,
  "Eh" DOUBLE PRECISION NOT NULL,
  "pe" DOUBLE PRECISION NOT NULL,
  "Ah" DOUBLE PRECISION NOT NULL,
  "pcH" DOUBLE PRECISION,
  "pHCl" DOUBLE PRECISION,
  "log_ionic_strength" DOUBLE PRECISION NOT NULL,
  "log_stoichiometric_ionic_strength" DOUBLE PRECISION NOT NULL,
  "ionic_asymmetry" DOUBLE PRECISION NOT NULL,
  "stoichiometric_ionic_asymmetry" DOUBLE PRECISION NOT NULL,
  "osmotic_coefficient" DOUBLE PRECISION NOT NULL,
  "stoichiometric_osmotic_coefficient" DOUBLE PRECISION NOT NULL,
  "log_sum_molalities" DOUBLE PRECISION NOT NULL,
  "log_sum_stoichiometric_molalities" DOUBLE PRECISION NOT NULL,
  "charge_imbalance" DOUBLE PRECISION NOT NULL,
  "expected_charge_imbalance" DOUBLE PRECISION,
  "sigma" DOUBLE PRECISION,
  "charge_discrepancy" DOUBLE PRECISION,
  "anions" DOUBLE PRECISION,
  "cations" DOUBLE PRECISION,
  "total_charge" DOUBLE PRECISION,
  "mean_charge" DOUBLE PRECISION,
  "solute_mass" DOUBLE PRECISION NOT NULL,
  "solvent_mass" DOUBLE PRECISION NOT NULL,
  "solution_mass" DOUBLE PRECISION NOT NULL,
  "solution_volume" DOUBLE PRECISION,
  "tds" DOUBLE PRECISION NOT NULL,
  "solute_fraction" DOUBLE PRECISION NOT NULL,
  "solvent_fraction" DOUBLE PRECISION NOT NULL,
  "extended_alkalinity" DOUBLE PRECISION,
  "overall_affinity" DOUBLE PRECISION,
  "reactant_mass_reacted" DOUBLE PRECISION,
  "reactant_mass_remaining" DOUBLE PRECISION,
  "solid_mass_change" DOUBLE PRECISION,
  "solid_mass_created" DOUBLE PRECISION,
  "solid_mass_destroyed" DOUBLE PRECISION,
  "solid_volume_change" DOUBLE PRECISION,
  "solid_volume_created" DOUBLE PRECISION,
  "solid_volume_destroyed" DOUBLE PRECISION,
  "start_date" TIMESTAMP NOT NULL,
  "complete_date" TIMESTAMP NOT NULL,
  "custom_properties" JSONB NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("variable_space_id") REFERENCES "variable_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_elements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_molality" DOUBLE PRECISION NOT NULL,
  "mass_fraction" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_aqueous_species" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_molality" DOUBLE PRECISION NOT NULL,
  "log_activity" DOUBLE PRECISION NOT NULL,
  "log_gamma" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_pure_solids" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_qk" DOUBLE PRECISION NOT NULL,
  "affinity" DOUBLE PRECISION NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  "log_mass" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  "log_volume" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_solid_solutions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_qk" DOUBLE PRECISION NOT NULL,
  "affinity" DOUBLE PRECISION NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  "log_mass" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  "log_volume" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_end_members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_solid_solution_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_qk" DOUBLE PRECISION NOT NULL,
  "affinity" DOUBLE PRECISION NOT NULL,
  "log_moles" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  "log_mass" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  "log_volume" DOUBLE PRECISION NOT NULL DEFAULT '-Infinity'::double precision,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_solid_solution_id") REFERENCES "equilibrium_solid_solutions"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_gases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "log_fugacity" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_reactants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "affinity" DOUBLE PRECISION NOT NULL,
  "relative_rate" DOUBLE PRECISION NOT NULL,
  "log_moles_reacted" DOUBLE PRECISION NOT NULL,
  "log_moles_remaining" DOUBLE PRECISION NOT NULL,
  "log_mass_reacted" DOUBLE PRECISION NOT NULL,
  "log_mass_remaining" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "equilibrium_redox_reactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "equilibrium_space_id" INTEGER NOT NULL,
  "couple" TEXT NOT NULL,
  "Eh" DOUBLE PRECISION NOT NULL,
  "pe" DOUBLE PRECISION NOT NULL,
  "log_fO2" DOUBLE PRECISION NOT NULL,
  "Ah" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("equilibrium_space_id") REFERENCES "equilibrium_space"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "orders_name_idx" ON "orders" ("name");

CREATE INDEX IF NOT EXISTS "orders_tag_idx" ON "orders" ("tag");

CREATE INDEX IF NOT EXISTS "orders_eleanor_version_idx" ON "orders" ("eleanor_version");

