"""Pre-built SQL templates for every table the sink writes or reads.

Each table in :data:`schema.TABLES` gets two pre-built psycopg
``SQL`` statements at module load time:

* ``INSERT INTO <table> (<cols>) VALUES (%(col1)s, ..., %(colN)s)`` --
  a named-parameter INSERT shaped to consume the dict produced by the
  matching converter in :mod:`converters`. Identity-PK columns are
  excluded so the DB autogenerates the id.
* ``INSERT ... RETURNING id`` -- the same INSERT with ``RETURNING id``
  appended, for tables whose autogenerated id the caller needs (every
  table whose children point at it via FK).

Building these once at module load means each ``cursor.executemany``
call avoids the per-statement compile-cache lookup that the previous SA
implementation was paying.

Read-side templates are minimal -- only the two queries
``repositories`` actually issues (``get_order``, ``get_scratch_entry``)
plus a placeholder ``SELECT 1`` we use as a connection sanity-check.
"""

from psycopg import sql

from . import schema


def _insert_columns(table: schema.TableDef) -> tuple[str, ...]:
    """Return the column names that go into an INSERT statement.

    Identity-PK columns (``id`` on most tables) are excluded so the DB
    autogenerates the id at INSERT time. Every other column is
    included, including FK columns and JSONB / BYTEA payloads.
    """
    return tuple(c.name for c in table.columns if not c.identity)


def _build_insert(table: schema.TableDef, returning: bool = False) -> sql.SQL | sql.Composed:
    """Build a named-parameter INSERT for ``table``.

    With ``returning=True`` an ``INSERT ... RETURNING id`` is produced;
    callers consume the returned id (typically the FK fanout target for
    a follow-up bulk INSERT into a child table).
    """
    cols = _insert_columns(table)
    column_list = sql.SQL(", ").join(sql.Identifier(c) for c in cols)
    placeholder_list = sql.SQL(", ").join(sql.Placeholder(c) for c in cols)
    statement: sql.SQL | sql.Composed = sql.SQL("INSERT INTO {table} ({cols}) VALUES ({values})").format(
        table=sql.Identifier(table.name),
        cols=column_list,
        values=placeholder_list,
    )
    if returning:
        statement = sql.SQL("{insert} RETURNING {id}").format(
            insert=statement,
            id=sql.Identifier("id"),
        )
    return statement


# Tables we always need the autogenerated id for (because something else
# FK-references them), built with RETURNING id. The remaining tables are
# leaf rows; we still RETURN id from them for consistency with executemany
# but the sink doesn't always read it.

INSERTS: dict[str, sql.SQL | sql.Composed] = {
    table.name: _build_insert(table, returning=False) for table in schema.TABLES
}

INSERTS_RETURNING_ID: dict[str, sql.SQL | sql.Composed] = {
    table.name: _build_insert(table, returning=True) for table in schema.TABLES
}


SELECT_ORDER: sql.SQL = sql.SQL("SELECT id, name, tag, eleanor_version, raw, create_date FROM orders WHERE id = %s")


SELECT_SCRATCH_ENTRY: sql.SQL = sql.SQL(
    "SELECT vs.id AS variable_space_id, vs.exit_code, sc.zip FROM variable_space AS vs LEFT JOIN scratch AS sc ON sc.id = vs.id WHERE vs.id = %s"
)


SELECT_VS_POINT_EXISTS: sql.SQL = sql.SQL("SELECT 1 FROM variable_space WHERE id = %s")
