from collections.abc import Generator
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import LiteralString

import psycopg
from psycopg import sql

from eleanor.typing import cast


@dataclass(frozen=True, slots=True)
class ColumnDef(object):
    """A single column in a :class:`TableDef`.

    ``default`` is a raw SQL fragment (e.g. ``"''"`` for an empty string,
    ``"'-Infinity'::double precision"`` for ``-np.inf``); the emitter
    splices it directly into the ``DEFAULT ...`` clause.

    ``identity`` marks an auto-incrementing integer primary key; the
    emitter renders it as ``GENERATED BY DEFAULT AS IDENTITY``, which is
    read/write-compatible with the ``SERIAL`` columns any pre-rewrite
    database may already carry.
    """

    name: str
    sql_type: str
    nullable: bool = True
    default: str | None = None
    identity: bool = False


@dataclass(frozen=True, slots=True)
class ForeignKeyDef(object):
    """A foreign-key constraint.

    Default is ``ON DELETE CASCADE`` so removing a parent row sweeps the
    children -- the sink's row hierarchy is strictly tree-shaped, so
    leaf rows are never independently meaningful.
    """

    column: str
    references_table: str
    references_column: str = "id"
    on_delete: str = "CASCADE"


@dataclass(frozen=True, slots=True)
class CheckDef(object):
    """A named ``CHECK`` constraint.

    ``expression`` is a raw SQL fragment written in terms of the table's
    columns (e.g. ``"name is not null or type is not null"``).
    """

    name: str
    expression: str


@dataclass(frozen=True, slots=True)
class IndexDef(object):
    """A secondary index.

    Primary-key indexes are implied by :attr:`TableDef.primary_key` and
    must not be redeclared here.
    """

    name: str
    columns: tuple[str, ...]
    unique: bool = False


@dataclass(frozen=True, slots=True)
class TableDef(object):
    """The complete description of a table the sink owns.

    The dependency order of :data:`TABLES` matches FK dependencies, so
    :func:`ensure_schema` can emit ``CREATE TABLE`` statements in list
    order without forward-reference errors.
    """

    name: str
    columns: tuple[ColumnDef, ...]
    primary_key: tuple[str, ...] = ()
    foreign_keys: tuple[ForeignKeyDef, ...] = ()
    checks: tuple[CheckDef, ...] = ()
    indexes: tuple[IndexDef, ...] = field(default_factory=tuple)


def _quote_ident(name: str) -> str:
    """Render ``name`` as a double-quoted SQL identifier.

    Postgres folds unquoted identifiers to lowercase, so a column declared
    as ``pH`` would be created as ``ph`` and then refuse INSERTs that
    spell it ``"pH"`` (which is what :class:`psycopg.sql.Identifier`
    emits at the call site). Routing every identifier through
    :class:`sql.Identifier` here keeps the DDL and the INSERT path on the
    same case-preserved spelling, so mixed-case names like ``pH``,
    ``Eh``, ``log_fO2`` survive end-to-end.
    """
    return sql.Identifier(name).as_string(None)


def _quote_idents(names: tuple[str, ...] | list[str]) -> str:
    """Comma-join ``names`` after quoting each one."""
    return ", ".join(_quote_ident(n) for n in names)


def _column_sql(col: ColumnDef) -> str:
    parts: list[str] = [_quote_ident(col.name), col.sql_type]
    if col.identity:
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    if not col.nullable:
        parts.append("NOT NULL")
    if col.default is not None:
        parts.append(f"DEFAULT {col.default}")
    return " ".join(parts)


def to_create_table_sql(table: TableDef) -> str:
    """Render ``CREATE TABLE IF NOT EXISTS`` for ``table``."""
    parts: list[str] = [_column_sql(c) for c in table.columns]
    if table.primary_key:
        parts.append(f"PRIMARY KEY ({_quote_idents(table.primary_key)})")
    for fk in table.foreign_keys:
        fk_col = _quote_ident(fk.column)
        ref_table = _quote_ident(fk.references_table)
        ref_col = _quote_ident(fk.references_column)
        parts.append(f"FOREIGN KEY ({fk_col}) REFERENCES {ref_table}({ref_col}) ON DELETE {fk.on_delete}")
    for ck in table.checks:
        # ``ck.expression`` is raw SQL authored alongside the table; if it
        # references a mixed-case column it must quote that name itself.
        parts.append(f"CONSTRAINT {_quote_ident(ck.name)} CHECK ({ck.expression})")
    body = ",\n  ".join(parts)
    return f"CREATE TABLE IF NOT EXISTS {_quote_ident(table.name)} (\n  {body}\n)"


def to_create_index_sql(table: TableDef, idx: IndexDef) -> str:
    """Render ``CREATE INDEX IF NOT EXISTS`` for ``idx`` on ``table``."""
    unique = "UNIQUE " if idx.unique else ""
    idx_name = _quote_ident(idx.name)
    table_name = _quote_ident(table.name)
    cols = _quote_idents(idx.columns)
    return f"CREATE {unique}INDEX IF NOT EXISTS {idx_name} ON {table_name} ({cols})"


def to_drop_index_sql(idx: IndexDef) -> str:
    """Render ``DROP INDEX IF EXISTS`` for ``idx``. Used by the bulk-load lifecycle."""
    return f"DROP INDEX IF EXISTS {_quote_ident(idx.name)}"


# Postgres' ``NAMEDATALEN - 1`` identifier limit. Names longer than this
# are silently truncated by the server, so we truncate to the same length
# when synthesising constraint names. That keeps the names we emit in
# ``ALTER TABLE ... ADD CONSTRAINT`` aligned with what
# ``information_schema.table_constraints`` returns after the server's own
# auto-truncation has kicked in.
_PG_MAX_IDENT_LEN: int = 63


def _fk_constraint_name(table_name: str, fk_column: str) -> str:
    """Synthesise PG's default ``<table>_<column>_fkey`` FK constraint name.

    Postgres auto-generates exactly this shape when an inline
    ``FOREIGN KEY (...)`` clause is declared without a ``CONSTRAINT``
    name (which is what :func:`to_create_table_sql` does). Reusing the
    same convention here means :func:`recreate_indexes` produces names
    that are byte-for-byte identical to the ones the server picked when
    the table was first created, so the recreated FK is
    indistinguishable from the inline-declared one.
    """
    return f"{table_name}_{fk_column}_fkey"[:_PG_MAX_IDENT_LEN]


def to_drop_constraint_sql(table_name: str, constraint_name: str) -> str:
    """Render ``ALTER TABLE ... DROP CONSTRAINT IF EXISTS`` for ``constraint_name``.

    Idempotent thanks to ``IF EXISTS``; safe to call when the constraint
    has already been dropped manually or has not yet been added.
    """
    return f"ALTER TABLE {_quote_ident(table_name)} DROP CONSTRAINT IF EXISTS {_quote_ident(constraint_name)}"


def to_add_foreign_key_sql(table: TableDef, fk: ForeignKeyDef) -> str:
    """Render ``ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY ...`` for ``fk``.

    The constraint name comes from :func:`_fk_constraint_name`, matching
    Postgres' own ``<table>_<column>_fkey`` convention. ``ON DELETE``
    semantics are preserved verbatim from the :class:`ForeignKeyDef`.
    """
    name = _fk_constraint_name(table.name, fk.column)
    return (
        f"ALTER TABLE {_quote_ident(table.name)} "
        f"ADD CONSTRAINT {_quote_ident(name)} "
        f"FOREIGN KEY ({_quote_ident(fk.column)}) "
        f"REFERENCES {_quote_ident(fk.references_table)}"
        f"({_quote_ident(fk.references_column)}) "
        f"ON DELETE {fk.on_delete}"
    )


def to_add_check_sql(table: TableDef, check: CheckDef) -> str:
    """Render ``ALTER TABLE ... ADD CONSTRAINT ... CHECK ...`` for ``check``.

    The constraint name is :attr:`CheckDef.name`, which is also what the
    table-level DDL emits inline, so a recreated CHECK is
    indistinguishable from the inline-declared one.
    """
    return (
        f"ALTER TABLE {_quote_ident(table.name)} ADD CONSTRAINT {_quote_ident(check.name)} CHECK ({check.expression})"
    )


def _run_ddl(cursor: psycopg.Cursor, ddl: str) -> None:
    """Execute a DDL string built by our own emitter.

    psycopg3 types :meth:`psycopg.Cursor.execute` as accepting
    ``LiteralString | bytes | sql.SQL | sql.Composed``. Our DDL is
    constructed at runtime from constant table/column-name literals via
    :func:`to_create_table_sql`, so the cast is safe at the application
    level: there is no path where a caller-supplied string can land
    here.
    """
    _ = cursor.execute(cast(LiteralString, ddl))


_INSPECT_SCHEMA_QUERY: LiteralString = (
    "SELECT column_name, data_type, is_nullable "
    "FROM information_schema.columns "
    "WHERE table_schema = %s AND table_name = %s "
    "ORDER BY ordinal_position"
)


_LIST_CONSTRAINTS_QUERY: LiteralString = (
    "SELECT constraint_name FROM information_schema.table_constraints "
    "WHERE table_schema = %s AND table_name = %s AND constraint_type = %s"
)


def ensure_schema(connection: psycopg.Connection) -> None:
    """Create every table + index in :data:`TABLES` if they don't already exist.

    Idempotent. Runs all DDL inside a single transaction so a partial
    schema never lands. Safe to call repeatedly across runs.
    """
    with connection.transaction():
        with connection.cursor() as cur:
            for table in TABLES:
                _run_ddl(cur, to_create_table_sql(table))
            for table in TABLES:
                for idx in table.indexes:
                    _run_ddl(cur, to_create_index_sql(table, idx))


def inspect_schema(
    connection: psycopg.Connection,
    table_names: tuple[str, ...] | None = None,
) -> dict[str, list[tuple[str, str, bool]]]:
    """Return the live ``(column_name, data_type, is_nullable)`` shape of tables.

    Used by tests and the (future) EQL conformance check to verify that the
    DB matches what the schema definition expects. ``table_names`` defaults
    to every table the sink declares.
    """
    if table_names is None:
        table_names = tuple(t.name for t in TABLES)
    out: dict[str, list[tuple[str, str, bool]]] = {}
    with connection.cursor() as cur:
        for name in table_names:
            _ = cur.execute(_INSPECT_SCHEMA_QUERY, ("public", name))
            rows: list[tuple[str, str, bool]] = []
            for row in cur:
                # Pin the loosely-typed psycopg row to our 3-tuple shape.
                typed_row = cast(tuple[str, str, str], row)
                rows.append((typed_row[0], typed_row[1], typed_row[2] == "YES"))
            if rows:
                out[name] = rows
    return out


def drop_indexes(connection: psycopg.Connection) -> None:
    """Drop every secondary index + FK / CHECK constraint declared on :data:`TABLES`.

    Idempotent: every individual statement is ``IF EXISTS``-shaped, so
    calling this on a database that has already had its constraints
    stripped is a no-op.

    The FK pass introspects ``information_schema.table_constraints`` so
    it picks up constraints regardless of whether they were created
    with an explicit name or with PG's default ``<table>_<column>_fkey``
    naming. CHECK constraints are dropped by the names declared in
    :data:`TABLES`; PG's implicit ``NOT NULL`` constraints are stored on
    ``pg_attribute`` (not ``table_constraints``) on modern PostgreSQL
    and are intentionally untouched.

    All DDL runs inside a single transaction so a partial drop never
    lands. Run this once before a bulk-load workload starts; pair with
    :func:`recreate_indexes` (or the :func:`bulk_load_window` context
    manager) to put everything back when the workload completes.
    """
    with connection.transaction():
        with connection.cursor() as cur:
            for table in TABLES:
                # FKs: introspect the live database so we drop whatever
                # is actually there, named or not.
                _ = cur.execute(
                    _LIST_CONSTRAINTS_QUERY,
                    ("public", table.name, "FOREIGN KEY"),
                )
                fk_names = [cast(str, row[0]) for row in cur.fetchall()]
                for fk_name in fk_names:
                    _run_ddl(cur, to_drop_constraint_sql(table.name, fk_name))
                # CHECK constraints: drop by declared name. ``IF EXISTS``
                # makes this idempotent for fresh databases that have
                # not yet had the constraint added.
                for check in table.checks:
                    _run_ddl(cur, to_drop_constraint_sql(table.name, check.name))
                # Indexes: drop by declared name.
                for idx in table.indexes:
                    _run_ddl(cur, to_drop_index_sql(idx))


def recreate_indexes(connection: psycopg.Connection) -> None:
    """Recreate every secondary index + FK / CHECK constraint declared on :data:`TABLES`.

    Indexes are added with ``CREATE INDEX IF NOT EXISTS`` (idempotent);
    ``ALTER TABLE ... ADD CONSTRAINT`` is *not* idempotent on its own,
    so the caller is expected to have run :func:`drop_indexes` first
    (or this function is being called as the recreate phase of a
    :func:`bulk_load_window`).

    Order matches :data:`TABLES` (parents before children); within each
    table indexes are added first (cheapest, no scan), then CHECK
    constraints, then FK constraints (most expensive, requires a scan
    of every row to validate against the parent).

    Runs all DDL inside a single transaction so a partial recreate
    never lands. If a constraint addition fails (typically because the
    bulk-loaded data violates the constraint), the whole transaction
    rolls back and the caller can fix the data and re-run.
    """
    with connection.transaction():
        with connection.cursor() as cur:
            for table in TABLES:
                for idx in table.indexes:
                    _run_ddl(cur, to_create_index_sql(table, idx))
                for check in table.checks:
                    _run_ddl(cur, to_add_check_sql(table, check))
                for fk in table.foreign_keys:
                    _run_ddl(cur, to_add_foreign_key_sql(table, fk))


@contextmanager
def bulk_load_window(connection: psycopg.Connection) -> Generator[None]:
    """Drop secondary constraints / indexes on enter; recreate them on exit.

    Symmetric guard around a bulk-load workload::

        with schema.bulk_load_window(conn):
            # bulk INSERT / COPY work happens here, with FK / CHECK /
            # secondary-index overhead disabled.
            ...

    The recreate runs in :keyword:`finally`, so an exception inside the
    ``with`` body still restores the constraints. If the recreate phase
    itself fails -- typically because the bulk-loaded data violates a
    constraint -- the exception propagates and the database is left
    with constraints missing; the caller can fix the data and re-run
    :func:`recreate_indexes` to finish the job.

    :func:`drop_indexes` and :func:`recreate_indexes` each open their
    own transaction, so the drop commits before the body runs and the
    recreate commits after the body returns. The body is free to manage
    its own transactions however the workload demands.
    """
    drop_indexes(connection)
    try:
        yield
    finally:
        recreate_indexes(connection)


def _identity_pk() -> ColumnDef:
    """The shared ``id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL`` column."""
    return ColumnDef("id", "INTEGER", nullable=False, identity=True)


def _vs_id_fk_column() -> ColumnDef:
    return ColumnDef("variable_space_id", "INTEGER", nullable=False)


def _es_id_fk_column() -> ColumnDef:
    return ColumnDef("equilibrium_space_id", "INTEGER", nullable=False)


def _double_neg_inf() -> str:
    """SQL literal for ``-np.inf`` in a ``DOUBLE PRECISION`` column."""
    return "'-Infinity'::double precision"


def _reactant_table(
    name: str,
    fk_target: str = "variable_space",
    fk_column: str = "variable_space_id",
) -> TableDef:
    return TableDef(
        name=name,
        columns=(
            _identity_pk(),
            ColumnDef(fk_column, "INTEGER", nullable=False),
            ColumnDef("name", "TEXT", nullable=False),
            ColumnDef("log_moles", "DOUBLE PRECISION", nullable=False),
            ColumnDef("titration_rate", "DOUBLE PRECISION", nullable=False),
        ),
        primary_key=("id",),
        foreign_keys=(ForeignKeyDef(fk_column, fk_target),),
    )


_SS_COLUMNS: tuple[ColumnDef, ...] = (
    ColumnDef("name", "TEXT", nullable=False),
    ColumnDef("log_qk", "DOUBLE PRECISION", nullable=False),
    ColumnDef("affinity", "DOUBLE PRECISION", nullable=False),
    ColumnDef("log_moles", "DOUBLE PRECISION", nullable=False, default=_double_neg_inf()),
    ColumnDef("log_mass", "DOUBLE PRECISION", nullable=False, default=_double_neg_inf()),
    ColumnDef("log_volume", "DOUBLE PRECISION", nullable=False, default=_double_neg_inf()),
)


ORDERS = TableDef(
    name="orders",
    columns=(
        _identity_pk(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("tag", "TEXT", nullable=False, default="''"),
        ColumnDef("eleanor_version", "TEXT", nullable=False),
        ColumnDef("raw", "JSONB", nullable=False),
        ColumnDef("create_date", "TIMESTAMP", nullable=False),
    ),
    primary_key=("id",),
    indexes=(
        IndexDef("orders_name_idx", ("name",)),
        IndexDef("orders_tag_idx", ("tag",)),
        IndexDef("orders_eleanor_version_idx", ("eleanor_version",)),
    ),
)


VARIABLE_SPACE = TableDef(
    name="variable_space",
    columns=(
        _identity_pk(),
        ColumnDef("order_id", "INTEGER", nullable=False),
        ColumnDef("water_mass", "DOUBLE PRECISION", nullable=False),
        ColumnDef("temperature", "DOUBLE PRECISION", nullable=False),
        ColumnDef("pressure", "DOUBLE PRECISION", nullable=False),
        ColumnDef("exit_code", "INTEGER", nullable=False),
        ColumnDef("create_date", "TIMESTAMP", nullable=False),
        ColumnDef("start_date", "TIMESTAMP", nullable=False),
        ColumnDef("complete_date", "TIMESTAMP", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("order_id", "orders"),),
)


KERNEL = TableDef(
    name="kernel",
    columns=(
        ColumnDef("id", "INTEGER", nullable=False),
        ColumnDef("type", "TEXT", nullable=False),
        ColumnDef("settings", "JSONB", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("id", "variable_space"),),
)


SCRATCH = TableDef(
    name="scratch",
    columns=(
        ColumnDef("id", "INTEGER", nullable=False),
        ColumnDef("zip", "BYTEA", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("id", "variable_space"),),
)


ELEMENTS = TableDef(
    name="elements",
    columns=(
        _identity_pk(),
        _vs_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("log_molality", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("variable_space_id", "variable_space"),),
)


SPECIES = TableDef(
    name="species",
    columns=(
        _identity_pk(),
        _vs_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("value", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("variable_space_id", "variable_space"),),
)


SUPPRESSIONS = TableDef(
    name="suppressions",
    columns=(
        _identity_pk(),
        _vs_id_fk_column(),
        ColumnDef("name", "TEXT"),
        ColumnDef("type", "TEXT"),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("variable_space_id", "variable_space"),),
    checks=(
        CheckDef(
            "suppressions_well_defined",
            "name is not null or type is not null",
        ),
    ),
)


SUPPRESSION_EXCEPTIONS = TableDef(
    name="suppression_exceptions",
    columns=(
        _identity_pk(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("suppression_id", "INTEGER", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("suppression_id", "suppressions"),),
)


MINERAL_REACTANTS = _reactant_table("mineral_reactants")
AQUEOUS_REACTANTS = _reactant_table("aqueous_reactants")
GAS_REACTANTS = _reactant_table("gas_reactants")
ELEMENT_REACTANTS = _reactant_table("element_reactants")


SPECIAL_REACTANTS = _reactant_table("special_reactants")
SPECIAL_REACTANT_COMPOSITIONS = TableDef(
    name="special_reactant_compositions",
    columns=(
        _identity_pk(),
        ColumnDef("special_reactant_id", "INTEGER", nullable=False),
        ColumnDef("element", "TEXT", nullable=False),
        ColumnDef("count", "INTEGER", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("special_reactant_id", "special_reactants"),),
)


FIXED_GAS_REACTANTS = TableDef(
    name="fixed_gas_reactants",
    columns=(
        _identity_pk(),
        _vs_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("log_moles", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_fugacity", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("variable_space_id", "variable_space"),),
)


SOLID_SOLUTION_REACTANTS = _reactant_table("solid_solution_reactants")
SOLID_SOLUTION_REACTANT_END_MEMBERS = TableDef(
    name="solid_solution_reactant_end_members",
    columns=(
        _identity_pk(),
        ColumnDef("solid_solution_reactant_id", "INTEGER", nullable=False),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("fraction", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("solid_solution_reactant_id", "solid_solution_reactants"),),
    checks=(CheckDef("fraction_in_range", "0.0 <= fraction AND fraction <= 1.0"),),
)


EQUILIBRIUM_SPACE = TableDef(
    name="equilibrium_space",
    columns=(
        _identity_pk(),
        ColumnDef("variable_space_id", "INTEGER"),
        ColumnDef("stage", "TEXT", nullable=False),
        ColumnDef("log_xi", "DOUBLE PRECISION"),
        ColumnDef("temperature", "DOUBLE PRECISION", nullable=False),
        ColumnDef("pressure", "DOUBLE PRECISION", nullable=False),
        ColumnDef("pH", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_fO2", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_activity_water", "DOUBLE PRECISION", nullable=False),
        ColumnDef("mole_fraction_water", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_gamma_water", "DOUBLE PRECISION", nullable=False),
        ColumnDef("Eh", "DOUBLE PRECISION", nullable=False),
        ColumnDef("pe", "DOUBLE PRECISION", nullable=False),
        ColumnDef("Ah", "DOUBLE PRECISION", nullable=False),
        ColumnDef("pcH", "DOUBLE PRECISION"),
        ColumnDef("pHCl", "DOUBLE PRECISION"),
        ColumnDef("log_ionic_strength", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_stoichiometric_ionic_strength", "DOUBLE PRECISION", nullable=False),
        ColumnDef("ionic_asymmetry", "DOUBLE PRECISION", nullable=False),
        ColumnDef("stoichiometric_ionic_asymmetry", "DOUBLE PRECISION", nullable=False),
        ColumnDef("osmotic_coefficient", "DOUBLE PRECISION", nullable=False),
        ColumnDef("stoichiometric_osmotic_coefficient", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_sum_molalities", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_sum_stoichiometric_molalities", "DOUBLE PRECISION", nullable=False),
        ColumnDef("charge_imbalance", "DOUBLE PRECISION", nullable=False),
        ColumnDef("expected_charge_imbalance", "DOUBLE PRECISION"),
        ColumnDef("sigma", "DOUBLE PRECISION"),
        ColumnDef("charge_discrepancy", "DOUBLE PRECISION"),
        ColumnDef("anions", "DOUBLE PRECISION"),
        ColumnDef("cations", "DOUBLE PRECISION"),
        ColumnDef("total_charge", "DOUBLE PRECISION"),
        ColumnDef("mean_charge", "DOUBLE PRECISION"),
        ColumnDef("solute_mass", "DOUBLE PRECISION", nullable=False),
        ColumnDef("solvent_mass", "DOUBLE PRECISION", nullable=False),
        ColumnDef("solution_mass", "DOUBLE PRECISION", nullable=False),
        ColumnDef("solution_volume", "DOUBLE PRECISION"),
        ColumnDef("tds", "DOUBLE PRECISION", nullable=False),
        ColumnDef("solute_fraction", "DOUBLE PRECISION", nullable=False),
        ColumnDef("solvent_fraction", "DOUBLE PRECISION", nullable=False),
        ColumnDef("extended_alkalinity", "DOUBLE PRECISION"),
        ColumnDef("overall_affinity", "DOUBLE PRECISION"),
        ColumnDef("reactant_mass_reacted", "DOUBLE PRECISION"),
        ColumnDef("reactant_mass_remaining", "DOUBLE PRECISION"),
        ColumnDef("solid_mass_change", "DOUBLE PRECISION"),
        ColumnDef("solid_mass_created", "DOUBLE PRECISION"),
        ColumnDef("solid_mass_destroyed", "DOUBLE PRECISION"),
        ColumnDef("solid_volume_change", "DOUBLE PRECISION"),
        ColumnDef("solid_volume_created", "DOUBLE PRECISION"),
        ColumnDef("solid_volume_destroyed", "DOUBLE PRECISION"),
        ColumnDef("start_date", "TIMESTAMP", nullable=False),
        ColumnDef("complete_date", "TIMESTAMP", nullable=False),
        ColumnDef("custom_properties", "JSONB", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("variable_space_id", "variable_space"),),
)


EQUILIBRIUM_ELEMENTS = TableDef(
    name="equilibrium_elements",
    columns=(
        _identity_pk(),
        _es_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("log_molality", "DOUBLE PRECISION", nullable=False),
        ColumnDef("mass_fraction", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


EQUILIBRIUM_AQUEOUS_SPECIES = TableDef(
    name="equilibrium_aqueous_species",
    columns=(
        _identity_pk(),
        _es_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("log_molality", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_activity", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_gamma", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


EQUILIBRIUM_PURE_SOLIDS = TableDef(
    name="equilibrium_pure_solids",
    columns=(_identity_pk(), _es_id_fk_column(), *_SS_COLUMNS),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


EQUILIBRIUM_SOLID_SOLUTIONS = TableDef(
    name="equilibrium_solid_solutions",
    columns=(_identity_pk(), _es_id_fk_column(), *_SS_COLUMNS),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


EQUILIBRIUM_END_MEMBERS = TableDef(
    name="equilibrium_end_members",
    columns=(
        _identity_pk(),
        ColumnDef("equilibrium_solid_solution_id", "INTEGER", nullable=False),
        *_SS_COLUMNS,
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_solid_solution_id", "equilibrium_solid_solutions"),),
)


EQUILIBRIUM_GASES = TableDef(
    name="equilibrium_gases",
    columns=(
        _identity_pk(),
        _es_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("log_fugacity", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


EQUILIBRIUM_REACTANTS = TableDef(
    name="equilibrium_reactants",
    columns=(
        _identity_pk(),
        _es_id_fk_column(),
        ColumnDef("name", "TEXT", nullable=False),
        ColumnDef("affinity", "DOUBLE PRECISION", nullable=False),
        ColumnDef("relative_rate", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_moles_reacted", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_moles_remaining", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_mass_reacted", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_mass_remaining", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


EQUILIBRIUM_REDOX_REACTIONS = TableDef(
    name="equilibrium_redox_reactions",
    columns=(
        _identity_pk(),
        _es_id_fk_column(),
        ColumnDef("couple", "TEXT", nullable=False),
        ColumnDef("Eh", "DOUBLE PRECISION", nullable=False),
        ColumnDef("pe", "DOUBLE PRECISION", nullable=False),
        ColumnDef("log_fO2", "DOUBLE PRECISION", nullable=False),
        ColumnDef("Ah", "DOUBLE PRECISION", nullable=False),
    ),
    primary_key=("id",),
    foreign_keys=(ForeignKeyDef("equilibrium_space_id", "equilibrium_space"),),
)


TABLES: tuple[TableDef, ...] = (
    ORDERS,
    VARIABLE_SPACE,
    KERNEL,
    SCRATCH,
    ELEMENTS,
    SPECIES,
    SUPPRESSIONS,
    SUPPRESSION_EXCEPTIONS,
    MINERAL_REACTANTS,
    AQUEOUS_REACTANTS,
    GAS_REACTANTS,
    ELEMENT_REACTANTS,
    SPECIAL_REACTANTS,
    SPECIAL_REACTANT_COMPOSITIONS,
    FIXED_GAS_REACTANTS,
    SOLID_SOLUTION_REACTANTS,
    SOLID_SOLUTION_REACTANT_END_MEMBERS,
    EQUILIBRIUM_SPACE,
    EQUILIBRIUM_ELEMENTS,
    EQUILIBRIUM_AQUEOUS_SPECIES,
    EQUILIBRIUM_PURE_SOLIDS,
    EQUILIBRIUM_SOLID_SOLUTIONS,
    EQUILIBRIUM_END_MEMBERS,
    EQUILIBRIUM_GASES,
    EQUILIBRIUM_REACTANTS,
    EQUILIBRIUM_REDOX_REACTIONS,
)


# Lookup-by-name. Useful when callers want to dispatch on a table name
# (e.g. the ``StatementProfiler`` cross-referencing INSERT statements
# against the table list).
TABLES_BY_NAME: dict[str, TableDef] = {t.name: t for t in TABLES}


__all__ = [
    "ColumnDef",
    "ForeignKeyDef",
    "CheckDef",
    "IndexDef",
    "TableDef",
    "ORDERS",
    "VARIABLE_SPACE",
    "KERNEL",
    "SCRATCH",
    "ELEMENTS",
    "SPECIES",
    "SUPPRESSIONS",
    "SUPPRESSION_EXCEPTIONS",
    "MINERAL_REACTANTS",
    "AQUEOUS_REACTANTS",
    "GAS_REACTANTS",
    "ELEMENT_REACTANTS",
    "SPECIAL_REACTANTS",
    "SPECIAL_REACTANT_COMPOSITIONS",
    "FIXED_GAS_REACTANTS",
    "SOLID_SOLUTION_REACTANTS",
    "SOLID_SOLUTION_REACTANT_END_MEMBERS",
    "EQUILIBRIUM_SPACE",
    "EQUILIBRIUM_ELEMENTS",
    "EQUILIBRIUM_AQUEOUS_SPECIES",
    "EQUILIBRIUM_PURE_SOLIDS",
    "EQUILIBRIUM_SOLID_SOLUTIONS",
    "EQUILIBRIUM_END_MEMBERS",
    "EQUILIBRIUM_GASES",
    "EQUILIBRIUM_REACTANTS",
    "EQUILIBRIUM_REDOX_REACTIONS",
    "TABLES",
    "TABLES_BY_NAME",
    "to_create_table_sql",
    "to_create_index_sql",
    "to_drop_index_sql",
    "to_drop_constraint_sql",
    "to_add_foreign_key_sql",
    "to_add_check_sql",
    "ensure_schema",
    "inspect_schema",
    "drop_indexes",
    "recreate_indexes",
    "bulk_load_window",
]
