"""initial revision

Revision ID: 0a5036bfdc84
Revises: base
Create Date: 2025-04-18 11:45:38.939023

"""
from typing import Sequence, Union

import sqlalchemy as sa

import eleanor.yeoman
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a5036bfdc84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('hash', sa.String(), nullable=False),
        sa.Column('eleanor_version', sa.String(), nullable=False),
        sa.Column('kernel_version', sa.String(), nullable=False),
        sa.Column('raw', eleanor.yeoman.JSONDict(), nullable=False),
        sa.Column('create_date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_orders_hash'), 'orders', ['hash'], unique=False)
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    op.create_table(
        'huffer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('zip', eleanor.yeoman.Binary(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['orders.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'variable_space',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('temperature', sa.Double(), nullable=False),
        sa.Column('pressure', sa.Double(), nullable=False),
        sa.Column('exit_code', sa.Integer(), nullable=False),
        sa.Column('create_date', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'elements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variable_space_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_molality', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['variable_space_id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'equilibrium_space',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variable_space_id', sa.Integer(), nullable=True),
        sa.Column('kernel', sa.String(), nullable=False),
        sa.Column('temperature', sa.Double(), nullable=False),
        sa.Column('pressure', sa.Double(), nullable=False),
        sa.Column('pH', sa.Double(), nullable=False),
        sa.Column('log_fO2', sa.Double(), nullable=False),
        sa.Column('log_activity_water', sa.Double(), nullable=False),
        sa.Column('ionic_strength', sa.Double(), nullable=False),
        sa.Column('tds_mass', sa.Double(), nullable=False),
        sa.Column('solution_mass', sa.Double(), nullable=False),
        sa.Column('charge_imbalance', sa.Double(), nullable=False),
        sa.Column('extended_alkalinity', sa.Double(), nullable=True),
        sa.Column('initial_affinity', sa.Double(), nullable=True),
        sa.Column('log_xi', sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(['variable_space_id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'kernel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'reactants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variable_space_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['variable_space_id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'scratch',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('zip', eleanor.yeoman.Binary(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'species',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variable_space_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.Column('value', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['variable_space_id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'suppressions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variable_space_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.CheckConstraint('name is not null or type is not null', name='suppressions_well_defined'),
        sa.ForeignKeyConstraint(['variable_space_id'], ['variable_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'element_reactants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_moles', sa.Double(), nullable=False),
        sa.Column('log_titration_rate', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['reactants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'equilibrium_aqueous_species',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('equilibrium_space_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_molality', sa.Double(), nullable=False),
        sa.Column('log_activity', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['equilibrium_space_id'], ['equilibrium_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'equilibrium_elements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('equilibrium_space_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_molality', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['equilibrium_space_id'], ['equilibrium_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'equilibrium_gas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('equilibrium_space_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_fugacity', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['equilibrium_space_id'], ['equilibrium_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'equilibrium_solid_phase',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('equilibrium_space_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('end_member', sa.String(), nullable=True),
        sa.Column('log_qk', sa.Double(), nullable=False),
        sa.Column('affinity', sa.Double(), nullable=False),
        sa.Column('log_moles', sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(['equilibrium_space_id'], ['equilibrium_space.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'fixed_gas_reactants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_moles', sa.Double(), nullable=False),
        sa.Column('log_fugacity', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['reactants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'gas_reactants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_moles', sa.Double(), nullable=False),
        sa.Column('log_titration_rate', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['reactants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'mineral_reactants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_moles', sa.Double(), nullable=False),
        sa.Column('log_titration_rate', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['reactants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'special_reactants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('log_moles', sa.Double(), nullable=False),
        sa.Column('log_titration_rate', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['reactants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'suppression_exceptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('suppression_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['suppression_id'], ['suppressions.id']),
        sa.PrimaryKeyConstraint('id', 'suppression_id'),
    )
    op.create_table(
        'special_reactant_composition',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('special_reactant_id', sa.Integer(), nullable=False),
        sa.Column('element', sa.String(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['special_reactant_id'], ['special_reactants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_reactant_composition')
    op.drop_table('suppression_exceptions')
    op.drop_table('special_reactants')
    op.drop_table('mineral_reactants')
    op.drop_table('gas_reactants')
    op.drop_table('fixed_gas_reactants')
    op.drop_table('equilibrium_solid_phase')
    op.drop_table('equilibrium_gas')
    op.drop_table('equilibrium_elements')
    op.drop_table('equilibrium_aqueous_species')
    op.drop_table('element_reactants')
    op.drop_table('suppressions')
    op.drop_table('species')
    op.drop_table('scratch')
    op.drop_table('reactants')
    op.drop_table('kernel')
    op.drop_table('equilibrium_space')
    op.drop_table('elements')
    op.drop_table('variable_space')
    op.drop_table('huffer')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_hash'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
