from collections.abc import Sequence
from typing import override

from ..connection import DatabaseConfig
from ..exceptions import EleanorException
from ..order import Order
from ..progress import ProgressHandle
from ..version import __version__
from ..yeoman import Yeoman
from .interface import ComputeResult, OutputSink, WriteOutcome


class PostgresSink(OutputSink):
    config: DatabaseConfig
    verbose: bool
    #: Gates database setup. Intentionally per-instance and does not pickle
    _initialized: bool

    def __init__(self, config: DatabaseConfig, verbose: bool = False):
        self.config = config
        self.verbose = verbose
        self._initialized = False

    @override
    def begin_run(self, order: Order) -> int:
        with Yeoman(self.config, verbose=self.verbose) as yeoman:
            if not self._initialized:
                yeoman.setup()
                self._initialized = True

            if order.id is None:
                if order.eleanor_version is None:
                    order.eleanor_version = __version__

                # refresh=True causes Yeoman to populate order.id after the insert
                yeoman.write(order, refresh=True)
                if order.id is None:
                    raise EleanorException('order does not have an id after insert')
            else:
                existing = yeoman.get(Order, order.id)
                if existing is None:
                    # This code path intentionally allows a user to create an
                    # order with an ID of their choosing, e.g. they've developed
                    # some scheme for keeping track of an order's details based
                    # on the order's id.
                    if order.eleanor_version is None:
                        order.eleanor_version = __version__
                    yeoman.write(order, refresh=True)
                elif order.eleanor_version is None:
                    order.eleanor_version = existing.eleanor_version
                elif order.eleanor_version != existing.eleanor_version:
                    raise EleanorException('cannot extend an order generated by a different version of Eleanor')

            return order.id

    @override
    def write_batch(
        self,
        order_id: int,
        results: Sequence[ComputeResult],
        progress: ProgressHandle | None = None,
    ) -> list[WriteOutcome]:
        outcomes: list[WriteOutcome] = []

        with Yeoman(self.config, verbose=self.verbose) as yeoman:
            for result in results:
                try:
                    # point.order_id must be set before the ORM write as a required side-effect
                    point = result.point
                    point.order_id = order_id
                    yeoman.write(point, refresh=True)

                    if point.id is None:
                        raise EleanorException('variable space point does not have an id after insert')

                    outcomes.append(
                        WriteOutcome(
                            point_id=point.id,
                            exit_code=point.exit_code,
                            committed=True,
                        ))

                    # Tick the output bar once per durably-written row. Rows
                    # that raise above are intentionally skipped: the output
                    # bar counts only committed writes.
                    if progress is not None:
                        progress.tick()
                except Exception as e:
                    outcomes.append(
                        WriteOutcome(
                            point_id=None,
                            exit_code=-1,
                            committed=False,
                            error_message=str(e),
                        ))

        return outcomes

    @override
    def finalize(self) -> None:
        pass

    @override
    def supports_worker_writes(self) -> bool:
        return True

    @override
    def supports_progress(self) -> bool:
        return True
