import json
from pathlib import Path
from typing import TextIO

import click
import yaml

from eleanor.cli.util import config_from_args, config_options, sole_postgres_settings
from eleanor.exceptions import EleanorError
from eleanor.output.postgres.persistence.repositories import get_order
from eleanor.util import require_uuid_id

_PROPERTIES: tuple[str, ...] = (
    "name",
    "creator",
    "create_date",
    "tags",
    "notes",
    "eleanor_version",
    "seed",
    "kernel",
    "navigator",
    "water_mass",
    "temperature",
    "pressure",
    "elements",
    "species",
    "reactants",
    "suppressions",
    "constraints",
)


_OPTIONAL_PROPERTIES: frozenset[str] = frozenset(
    {
        "tags",
        "notes",
        "species",
        "reactants",
        "suppressions",
        "constraints",
    }
)


@click.command(name="order")
@click.option("-o", "--output", type=click.File("w"), default="-", help="Output file (default: stdout).")
@click.option(
    "-t",
    "--to",
    type=click.Choice(["json", "yaml"]),
    help="Output file format (default: yaml or inferred from file extension provided to -o)",
)
@click.option(
    "-e",
    "--keep-empty",
    is_flag=True,
    help="Output optional properties even if they are empty (e.g. None, {}, [], etc...)",
)
@click.argument("order_id", type=click.STRING)
@config_options()
def dump_order(
    output: TextIO, to: str | None, keep_empty: bool, order_id: str, config: str, database: str | None
) -> None:
    """Dump an order suitable for rerunning Eleanor."""

    settings = sole_postgres_settings(config_from_args(config, database), "dump order")
    if settings.database.database is None:
        msg = "no database provided"
        raise click.ClickException(msg)

    try:
        oid = require_uuid_id(order_id, "order")
    except EleanorError as e:
        raise click.ClickException(str(e)) from None

    row = get_order(settings.database, oid)
    if row is None:
        msg = f"no order found with id {oid}"
        raise click.ClickException(msg)

    order_raw = _prepare_order(row.raw, keep_empty=keep_empty)

    if to is None:
        filetype = Path(output.name).suffix.lower()
        to = "json" if filetype == ".json" else "yaml"

    match to:
        case "yaml":
            yaml.safe_dump(order_raw, output, allow_unicode=True, sort_keys=False)
        case "json":
            json.dump(order_raw, output, indent=2, ensure_ascii=False, sort_keys=False)
            _ = output.write("\n")
        case _:
            msg = f"unknown filetype target: {to!r}"
            raise click.ClickException(msg)


def _is_empty_value(value: object) -> bool:
    """Determine if a property counts as "empty" for the purposes of output."""
    return value is None or (isinstance(value, (str, dict, list, set)) and len(value) == 0)  # pyright: ignore[reportUnknownArgumentType]


def _prepare_order(raw: dict[str, object], keep_empty: bool = False) -> dict[str, object]:
    """Prepare and order for output.

    This amounts to canonically reordering and dropping or keeping empty
    optional properties per the `keep_empty` argument.
    """
    try:
        return {
            prop: raw[prop]
            for prop in _PROPERTIES
            if (keep_empty and prop in _OPTIONAL_PROPERTIES) or not _is_empty_value(raw[prop])
        }
    except KeyError as e:
        msg = f"order is missing the {e.args[0]!r} property; it was likely generated by older version of Eleanor"
        raise click.ClickException(msg) from e


__all__ = ["dump_order"]
