"""Integration tests for the postgres migration runner.

These tests require a live Postgres instance. Skip via missing
``ELEANOR_TEST_DATABASE_URL`` environment variable (handled by the
``pg_config`` fixture).

Note on equivalence-test circularity: while only ``0001`` exists, the
``test_migrations_reach_target_schema`` test compares the output of
``apply_pending_migrations`` against ``ensure_schema``, but ``0001`` was
generated from ``ensure_schema`` itself. The test is therefore partly
circular on day one. Its real value comes at ``0002+`` and as a regression
tripwire if ``0001`` ever bit-rots. (See PLAN.md D1 and MIGRATIONS.md.)
"""

import os
import threading
import urllib.parse
from collections.abc import Generator
from typing import cast

import psycopg
import pytest

from eleanor.exceptions import EleanorException
from eleanor.output.postgres.persistence import connection, migrations, schema
from eleanor.output.postgres.persistence.migrations import _advisory_lock
from eleanor.output.postgres.settings import PostgresDatabaseSettings

_DATABASE_URL_ENV = "ELEANOR_TEST_DATABASE_URL"


def _config_from_env() -> PostgresDatabaseSettings | None:
    url = os.environ.get(_DATABASE_URL_ENV)
    if not url:
        return None
    parsed = urllib.parse.urlparse(url)
    return PostgresDatabaseSettings(
        host=parsed.hostname,
        port=parsed.port,
        database=(parsed.path or "/").lstrip("/") or None,
        username=parsed.username,
        password=parsed.password,
    )


def _raw_connect(cfg: PostgresDatabaseSettings) -> psycopg.Connection:
    return psycopg.connect(
        host=cfg.host,
        port=cfg.port,
        dbname=cfg.database,
        user=cfg.username,
        password=cfg.password,
    )


@pytest.fixture(scope="session")
def pg_config() -> PostgresDatabaseSettings:
    cfg = _config_from_env()
    if cfg is None:
        pytest.skip(f"{_DATABASE_URL_ENV} not set")
    return cfg


@pytest.fixture
def clean_db(pg_config: PostgresDatabaseSettings) -> Generator[PostgresDatabaseSettings, None, None]:
    """Start each test with an empty public schema. Closes the connection cache before and after."""
    connection.close_connection(pg_config)
    with _raw_connect(pg_config) as raw:
        with raw.cursor() as cur:
            _ = cur.execute("DROP SCHEMA IF EXISTS public CASCADE")
            _ = cur.execute("CREATE SCHEMA public")
            _ = cur.execute("DROP SCHEMA IF EXISTS eleanor_twin CASCADE")
        raw.commit()
    yield pg_config
    connection.close_connection(pg_config)


def test_apply_pending_migrations_creates_schema_migrations_table(
    clean_db: PostgresDatabaseSettings,
) -> None:
    migrations.apply_pending_migrations(connection.connect(clean_db))
    with connection.connect(clean_db).cursor() as cur:
        _ = cur.execute("SELECT COUNT(*) FROM schema_migrations")
        row = cur.fetchone()
    assert row is not None and cast(int, row[0]) > 0


def test_apply_pending_migrations_records_every_migration(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    declared = migrations.discover()
    with conn.cursor() as cur:
        _ = cur.execute("SELECT version FROM schema_migrations ORDER BY version")
        applied = [cast(int, r[0]) for r in cur.fetchall()]
    assert applied == [m.version for m in declared]


def test_apply_pending_migrations_is_idempotent(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    with conn.cursor() as cur:
        _ = cur.execute("SELECT COUNT(*) FROM schema_migrations")
        row = cur.fetchone()
    first_count = cast(int, row[0]) if row is not None else -1
    migrations.apply_pending_migrations(conn)
    with conn.cursor() as cur:
        _ = cur.execute("SELECT COUNT(*) FROM schema_migrations")
        row = cur.fetchone()
    second_count = cast(int, row[0]) if row is not None else -2
    assert first_count == second_count


def test_apply_pending_migrations_refuses_untracked_database(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute("CREATE TABLE orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)")
    with pytest.raises(EleanorException, match="--stamp"):
        migrations.apply_pending_migrations(conn)


def test_apply_pending_migrations_handles_partial_history(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    declared = migrations.discover()
    assert len(declared) >= 1, "need at least one declared migration"
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations "
            "(version INTEGER PRIMARY KEY, name TEXT NOT NULL, "
            "applied_at TIMESTAMPTZ NOT NULL, eleanor_version TEXT NOT NULL)"
        )
        _ = cur.execute(
            "INSERT INTO schema_migrations (version, name, applied_at, eleanor_version) "
            "VALUES (1, 'initial_schema', NOW(), 'test')"
        )
    migrations.apply_pending_migrations(conn)
    with conn.cursor() as cur:
        _ = cur.execute("SELECT version FROM schema_migrations ORDER BY version")
        applied = [cast(int, r[0]) for r in cur.fetchall()]
    assert applied == [m.version for m in declared]


def test_migrations_reach_target_schema(clean_db: PostgresDatabaseSettings) -> None:
    """Apply migrations to public; compare to a twin built via ensure_schema.

    This test is partly circular while only 0001 exists (see module docstring).
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    migrated_cols = schema.inspect_schema(conn)

    with _raw_connect(clean_db) as twin_raw:
        with twin_raw.cursor() as cur:
            _ = cur.execute("CREATE SCHEMA eleanor_twin")
        twin_raw.commit()
        with twin_raw.cursor() as cur:
            _ = cur.execute("SET search_path TO eleanor_twin")
        schema.ensure_schema(twin_raw)
        twin_cols = schema.inspect_schema(twin_raw, schema_name="eleanor_twin")

        assert schema._columns_by_name(migrated_cols) == schema._columns_by_name(twin_cols)
        assert schema.live_index_names(conn) == schema.live_index_names(twin_raw, "eleanor_twin")
        assert schema.live_constraint_names(conn) == schema.live_constraint_names(twin_raw, "eleanor_twin")


def test_verify_against_tables_clean_after_migrate(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    problems = schema.verify_against_tables(conn)
    assert problems == []


def test_verify_against_tables_detects_missing_index(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute("DROP INDEX IF EXISTS orders_name_idx")
    problems = schema.verify_against_tables(conn)
    assert any("orders_name_idx" in p for p in problems)


def test_live_index_names_returns_declared_indexes(
    clean_db: PostgresDatabaseSettings,
) -> None:
    """Live smoke leg of the indisvalid coverage triangle (D3 in PLAN.md).

    Verifies the _LIVE_VALID_INDEXES_QUERY is syntactically and semantically
    correct against the real catalog, regardless of test-role privileges.
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    live = schema.live_index_names(conn)
    declared = schema.declared_index_names()
    assert live >= declared


def test_verify_treats_invalid_index_as_missing(
    clean_db: PostgresDatabaseSettings,
) -> None:
    """Privileged leg of the indisvalid coverage triangle (D3 in PLAN.md).

    Requires superuser (UPDATE pg_index permission). Skips if the test
    role lacks that permission. The other two legs in the triangle
    (unit mock + live smoke) run unconditionally and cover the consumer
    logic and reader query correctness independently.
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    try:
        with conn.transaction(), conn.cursor() as cur:
            _ = cur.execute("UPDATE pg_index SET indisvalid = false WHERE indexrelid = 'orders_name_idx'::regclass")
    except psycopg.errors.InsufficientPrivilege:
        pytest.skip("requires superuser role to UPDATE pg_index")
    except Exception as exc:
        pytest.skip(f"pg_index UPDATE not permitted: {exc}")

    problems = schema.verify_against_tables(conn)
    assert any("orders_name_idx" in p for p in problems), f"Expected 'orders_name_idx' in drift report, got: {problems}"


def test_advisory_lock_serializes_concurrent_callers(
    clean_db: PostgresDatabaseSettings,
) -> None:
    """Second caller blocks until the first releases the advisory lock."""
    lock_acquired = threading.Event()
    ok_to_release = threading.Event()
    second_done = threading.Event()
    errors: list[Exception] = []

    def hold_lock() -> None:
        try:
            conn1 = _raw_connect(clean_db)
            with _advisory_lock(conn1):
                lock_acquired.set()
                ok_to_release.wait(timeout=8.0)
        except Exception as exc:
            errors.append(exc)

    def run_apply() -> None:
        try:
            lock_acquired.wait(timeout=5.0)
            conn2 = _raw_connect(clean_db)
            migrations.apply_pending_migrations(conn2)
        except Exception as exc:
            errors.append(exc)
        finally:
            second_done.set()

    t1 = threading.Thread(target=hold_lock, daemon=True)
    t2 = threading.Thread(target=run_apply, daemon=True)
    t1.start()
    lock_acquired.wait(timeout=5.0)
    t2.start()

    import time

    time.sleep(0.4)
    assert not second_done.is_set(), "apply_pending_migrations returned before the advisory lock was released"

    ok_to_release.set()
    t1.join(timeout=5.0)
    t2.join(timeout=8.0)

    assert not errors, f"Thread errors: {errors}"
