"""Integration tests for the postgres migration runner.

These tests require a live Postgres instance. Skip via missing
``ELEANOR_TEST_DATABASE_URL`` environment variable (handled by the
``pg_config`` fixture).

Note on equivalence-test circularity: while only ``0001`` exists, the
``test_migrations_reach_target_schema`` test compares the output of
``apply_pending_migrations`` against ``ensure_schema``, but ``0001`` was
generated from ``ensure_schema`` itself. The test is therefore partly
circular on day one. Its real value comes at ``0002+`` and as a regression
tripwire if ``0001`` ever bit-rots.
"""

import os
import threading
import urllib.parse
import uuid
from collections.abc import Generator
from datetime import datetime
from typing import LiteralString, cast

import psycopg
import pytest
from eleanor.exceptions import EleanorError
from eleanor.output.postgres.persistence import connection, migrations, schema
from eleanor.output.postgres.persistence.migrations import _advisory_lock
from eleanor.output.postgres.settings import PostgresDatabaseSettings

_DATABASE_URL_ENV = "ELEANOR_TEST_DATABASE_URL"


def _config_from_env() -> PostgresDatabaseSettings | None:
    url = os.environ.get(_DATABASE_URL_ENV)
    if not url:
        return None
    parsed = urllib.parse.urlparse(url)
    return PostgresDatabaseSettings(
        host=parsed.hostname,
        port=parsed.port,
        database=(parsed.path or "/").lstrip("/") or None,
        username=parsed.username,
        password=parsed.password,
    )


def _raw_connect(cfg: PostgresDatabaseSettings) -> psycopg.Connection:
    return psycopg.connect(
        host=cfg.host,
        port=cfg.port,
        dbname=cfg.database,
        user=cfg.username,
        password=cfg.password,
    )


@pytest.fixture(scope="session")
def pg_config() -> PostgresDatabaseSettings:
    cfg = _config_from_env()
    if cfg is None:
        pytest.skip(f"{_DATABASE_URL_ENV} not set")
    return cfg


@pytest.fixture
def clean_db(
    pg_config: PostgresDatabaseSettings,
) -> Generator[PostgresDatabaseSettings, None, None]:
    """Start each test with an empty public schema. Closes the connection cache before and after."""
    connection.close_connection(pg_config)
    with _raw_connect(pg_config) as raw:
        with raw.cursor() as cur:
            _ = cur.execute("DROP SCHEMA IF EXISTS public CASCADE")
            _ = cur.execute("CREATE SCHEMA public")
            _ = cur.execute("DROP SCHEMA IF EXISTS eleanor_twin CASCADE")
        raw.commit()
    yield pg_config
    connection.close_connection(pg_config)


def test_apply_pending_migrations_creates_schema_migrations_table(
    clean_db: PostgresDatabaseSettings,
) -> None:
    migrations.apply_pending_migrations(connection.connect(clean_db))
    with connection.connect(clean_db).cursor() as cur:
        _ = cur.execute("SELECT COUNT(*) FROM schema_migrations")
        row = cur.fetchone()
    assert row is not None and cast(int, row[0]) > 0


def test_apply_pending_migrations_records_every_migration(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    declared = migrations.discover()
    with conn.cursor() as cur:
        _ = cur.execute("SELECT version FROM schema_migrations ORDER BY version")
        applied = [cast(int, r[0]) for r in cur.fetchall()]
    assert applied == [m.version for m in declared]


def test_apply_pending_migrations_is_idempotent(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    with conn.cursor() as cur:
        _ = cur.execute("SELECT COUNT(*) FROM schema_migrations")
        row = cur.fetchone()
    first_count = cast(int, row[0]) if row is not None else -1
    migrations.apply_pending_migrations(conn)
    with conn.cursor() as cur:
        _ = cur.execute("SELECT COUNT(*) FROM schema_migrations")
        row = cur.fetchone()
    second_count = cast(int, row[0]) if row is not None else -2
    assert first_count == second_count


def test_apply_pending_migrations_refuses_untracked_database(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute("CREATE TABLE orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)")
    with pytest.raises(EleanorError, match="--stamp"):
        migrations.apply_pending_migrations(conn)


def test_apply_pending_migrations_handles_partial_history(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    declared = migrations.discover()
    assert len(declared) >= 2, "need at least two declared migrations"
    # Simulate a database that carries the full initial schema but was stamped
    # manually (e.g. via --stamp) rather than run through the runner.  We
    # execute migration 1's SQL directly so every table exists, then create
    # and seed schema_migrations so apply_pending_migrations picks up from
    # migration 2 onward.
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute(cast(LiteralString, declared[0].sql))
        _ = cur.execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations "
            "(version INTEGER PRIMARY KEY, name TEXT NOT NULL, "
            "applied_at TIMESTAMPTZ NOT NULL, eleanor_version TEXT NOT NULL)"
        )
        _ = cur.execute(
            "INSERT INTO schema_migrations (version, name, applied_at, eleanor_version) "
            "VALUES (1, 'initial_schema', NOW(), 'test')"
        )
    migrations.apply_pending_migrations(conn)
    with conn.cursor() as cur:
        _ = cur.execute("SELECT version FROM schema_migrations ORDER BY version")
        applied = [cast(int, r[0]) for r in cur.fetchall()]
    assert applied == [m.version for m in declared]


def test_migrations_reach_target_schema(clean_db: PostgresDatabaseSettings) -> None:
    """Apply migrations to public; compare to a twin built via ensure_schema.

    This test is partly circular while only 0001 exists (see module docstring).
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    migrated_cols = schema.inspect_schema(conn)

    with _raw_connect(clean_db) as twin_raw:
        with twin_raw.cursor() as cur:
            _ = cur.execute("CREATE SCHEMA eleanor_twin")
        twin_raw.commit()
        with twin_raw.cursor() as cur:
            _ = cur.execute("SET search_path TO eleanor_twin")
        schema.ensure_schema(twin_raw)
        twin_cols = schema.inspect_schema(twin_raw, schema_name="eleanor_twin")

        assert schema._columns_by_name(migrated_cols) == schema._columns_by_name(twin_cols)
        assert schema.live_index_names(conn) == schema.live_index_names(twin_raw, "eleanor_twin")
        assert schema.live_constraint_names(conn) == schema.live_constraint_names(twin_raw, "eleanor_twin")


_CONSTRAINT_DEFS_QUERY: LiteralString = (
    "SELECT t.relname, c.conname, c.contype, pg_get_constraintdef(c.oid) "
    "FROM pg_constraint c "
    "JOIN pg_class t ON t.oid = c.conrelid "
    "JOIN pg_namespace n ON n.oid = t.relnamespace "
    "WHERE n.nspname = %s AND t.relname = ANY(%s)"
)

_INDEX_DEFS_QUERY: LiteralString = (
    "SELECT tablename, indexname, indexdef FROM pg_indexes WHERE schemaname = %s AND tablename = ANY(%s)"
)


def _definitions(
    conn: psycopg.Connection,
    query: LiteralString,
    schema_name: str,
) -> set[tuple[str, ...]]:
    """Return catalog object *definitions* for ``schema_name``, schema qualification stripped.

    ``pg_get_constraintdef`` and ``pg_indexes.indexdef`` render a table
    unqualified only when its schema is on the search path, so the two
    schemas under comparison would otherwise differ on the prefix alone.
    Setting the search path *and* stripping the prefix covers both
    renderings. Only tables :data:`schema.TABLES` declares are considered,
    so ``schema_migrations`` -- which the runner creates and
    ``ensure_schema`` does not -- stays out of the comparison.
    """
    names = [t.name for t in schema.TABLES]
    with conn.cursor() as cur:
        _ = cur.execute(cast(LiteralString, f"SET search_path TO {schema_name}"))
        _ = cur.execute(query, (schema_name, names))
        rows = cur.fetchall()
    return {tuple(str(col).replace(f"{schema_name}.", "") for col in row) for row in rows}


def test_migrations_reach_target_schema_definitions(clean_db: PostgresDatabaseSettings) -> None:
    """Apply migrations; compare object *definitions* against an ensure_schema twin.

    :func:`test_migrations_reach_target_schema` compares names -- which
    columns exist, which indexes and which FK/CHECK constraints. Names alone
    let a whole class of divergence through, and every member of that class
    has been observed in review: a foreign key rebuilt without its
    ``ON DELETE CASCADE``, an index recreated against the wrong table or
    column list, a primary key never re-added (``live_constraint_names``
    defaults to FK + CHECK, so ``'p'`` is not compared at all).

    Comparing ``pg_get_constraintdef`` and ``indexdef`` closes all of it.
    Every ``contype`` is included, which on PostgreSQL 18 also covers the
    named ``NOT NULL`` constraints it materialises in ``pg_constraint``:
    those are auto-named from the column at creation time and are *not*
    renamed by ``ALTER TABLE ... RENAME COLUMN``, so a migration that sets
    ``NOT NULL`` on scaffolding named ``foo_uuid`` before renaming it to
    ``foo_id`` leaves a permanently mismatched name. On PostgreSQL 17 no
    such rows exist and that leg compares empty to empty, so this test needs
    no version branch.
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)

    with _raw_connect(clean_db) as twin_raw:
        with twin_raw.cursor() as cur:
            _ = cur.execute("CREATE SCHEMA eleanor_twin")
            _ = cur.execute("SET search_path TO eleanor_twin")
        twin_raw.commit()
        schema.ensure_schema(twin_raw)

        for label, query in (("constraint", _CONSTRAINT_DEFS_QUERY), ("index", _INDEX_DEFS_QUERY)):
            migrated = _definitions(conn, query, "public")
            twin = _definitions(twin_raw, query, "eleanor_twin")
            assert migrated, f"no {label} definitions found in the migrated schema"
            assert migrated == twin, (
                f"{label} definitions diverge between the migrated schema and the "
                f"ensure_schema twin:\n"
                f"  migrated only: {sorted(migrated - twin)}\n"
                f"  twin only:     {sorted(twin - migrated)}"
            )


_ES_INSERT: LiteralString = (
    'INSERT INTO equilibrium_space (variable_space_id, stage, temperature, pressure, "pH", '
    '"log_fO2", "Eh", log_activity_water, log_ionic_strength, solute_mass, solvent_mass, '
    "solution_mass, tds, start_date, complete_date, custom_properties) "
    "VALUES (%s, %s, 25.0, 1.0, 7.0, -70.0, 0.0, 0.0, -3.0, 0.0, 1.0, 1.0, 0.0, %s, %s, '{}'::jsonb)"
)


def _apply_legacy_migrations(conn: psycopg.Connection) -> None:
    """Apply every migration *preceding* the UUID switch, leaving an integer-keyed schema.

    Selected by slug rather than version number so the split stays correct
    as migrations accumulate on either side of it.
    """
    declared = migrations.discover()
    switch = next(m for m in declared if m.slug == "switch_to_uuid_primary_keys")
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute(cast(LiteralString, schema.to_create_table_sql(schema.SCHEMA_MIGRATIONS)))
    for mig in declared:
        if mig.version < switch.version:
            migrations._apply_one(conn, mig)


def test_migration_backfill_derives_uuids_from_creation_time(clean_db: PostgresDatabaseSettings) -> None:
    """Seed an integer-keyed database, migrate it, and check the ids it produced.

    This is the only coverage of ``0008``'s data transformation, and of the
    ``pg17_uuidv7`` function it defines to perform it. That function matters
    disproportionately: PostgreSQL 18 ships a ``uuidv7()`` builtin, but 17 --
    which CI also targets -- does not, so on 17 this hand-rolled SQL is the
    *only* thing assigning a primary key to an existing row. A version nibble
    set wrong there would be invisible until something downstream cared.

    Rows are inserted in an order deliberately scrambled against their
    timestamps, so the integer sequence order and the creation order
    disagree. The backfill derives each UUID from the row's own
    ``create_date`` / ``start_date`` rather than from ``clock_timestamp()``,
    which means sorting by the new id must reproduce *creation* order, not
    insertion order. Getting this wrong would not fail loudly; it would just
    silently discard the ordering that UUIDv7 exists to carry.
    """
    conn = connection.connect(clean_db)
    _apply_legacy_migrations(conn)

    # (marker, create_date) inserted c, a, b -- so integer ids ascend in an
    # order that contradicts the timestamps.
    orders = [("order-c", datetime(2024, 3, 1)), ("order-a", datetime(2024, 1, 1)), ("order-b", datetime(2024, 2, 1))]
    points = [("vs-d", 4), ("vs-b", 2), ("vs-a", 1), ("vs-c", 3)]

    order_ids: dict[str, int] = {}
    with conn.transaction(), conn.cursor() as cur:
        for marker, created in orders:
            _ = cur.execute(
                "INSERT INTO orders (name, eleanor_version, raw, create_date) "
                "VALUES (%s, 'test', '{}'::jsonb, %s) RETURNING id",
                (marker, created),
            )
            row = cur.fetchone()
            assert row is not None
            order_ids[marker] = cast(int, row[0])

        for marker, day in points:
            created = datetime(2024, 6, day)
            _ = cur.execute(
                "INSERT INTO variable_space (order_id, water_mass, temperature, pressure, exit_code, "
                "error, create_date, start_date, complete_date) "
                "VALUES (%s, 1.0, 25.0, 1.0, 0, %s, %s, %s, %s) RETURNING id",
                (order_ids["order-a"], marker, created, created, created),
            )
            row = cur.fetchone()
            assert row is not None
            vs_id = cast(int, row[0])
            # A leaf child, to prove the FK remap kept each row with its parent.
            _ = cur.execute(
                "INSERT INTO elements (variable_space_id, name, log_molality) VALUES (%s, %s, -3.0)",
                (vs_id, f"{marker}-element"),
            )
            # equilibrium_space backfills from start_date, not create_date.
            _ = cur.execute(_ES_INSERT, (vs_id, f"{marker}-stage", created, created))

    migrations.apply_pending_migrations(conn)

    with conn.cursor() as cur:
        # Every surviving primary key is a version-7 UUID, all distinct.
        for table in ("orders", "variable_space", "equilibrium_space"):
            _ = cur.execute(cast(LiteralString, f"SELECT id FROM {table}"))  # noqa: S608 -- fixed literals
            ids = [cast(uuid.UUID, r[0]) for r in cur.fetchall()]
            assert ids, f"{table} lost its rows during the migration"
            assert all(isinstance(i, uuid.UUID) for i in ids), f"{table}.id is not a UUID"
            assert all(i.version == 7 for i in ids), f"{table}.id is not UUIDv7: {[i.version for i in ids]}"
            assert len(set(ids)) == len(ids), f"{table}.id collided"

        # Sorting by the new id reproduces creation order, not insertion order.
        _ = cur.execute("SELECT name FROM orders ORDER BY id")
        assert [r[0] for r in cur.fetchall()] == ["order-a", "order-b", "order-c"]

        _ = cur.execute("SELECT error FROM variable_space ORDER BY id")
        assert [r[0] for r in cur.fetchall()] == ["vs-a", "vs-b", "vs-c", "vs-d"]

        _ = cur.execute("SELECT stage FROM equilibrium_space ORDER BY id")
        assert [r[0] for r in cur.fetchall()] == ["vs-a-stage", "vs-b-stage", "vs-c-stage", "vs-d-stage"]

        # The FK remap kept every child with the parent it started under.
        _ = cur.execute(
            "SELECT e.name, vs.error, o.name FROM elements e "
            "JOIN variable_space vs ON vs.id = e.variable_space_id "
            "JOIN orders o ON o.id = vs.order_id ORDER BY e.name"
        )
        assert cur.fetchall() == [(f"{m}-element", m, "order-a") for m, _ in sorted(points)]

        # The helper function is scaffolding and must not outlive the migration.
        _ = cur.execute("SELECT to_regprocedure('pg17_uuidv7(timestamp)') IS NULL")
        row = cur.fetchone()
        assert row is not None
        assert row[0], "pg17_uuidv7 outlived the migration that defined it"


def test_verify_against_tables_clean_after_migrate(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    problems = schema.verify_against_tables(conn)
    assert problems == []


@pytest.mark.parametrize(
    ("mutation", "column"),
    [
        ("ALTER TABLE orders ALTER COLUMN name DROP NOT NULL", "name"),
        ("ALTER TABLE orders ALTER COLUMN eleanor_version TYPE VARCHAR(64)", "eleanor_version"),
    ],
)
def test_verify_against_tables_detects_column_drift(
    clean_db: PostgresDatabaseSettings,
    mutation: str,
    column: str,
) -> None:
    """A column whose type or nullability diverges from ``TABLES`` is reported.

    ``verify_against_tables`` compares ``(type, nullable)`` per column, but
    only the *presence* leg had coverage. The nullability leg is what catches
    a :class:`ColumnDef` that loses its ``nullable=False``: on a primary key
    that mistake still emits valid DDL, because Postgres makes a PK implicitly
    ``NOT NULL``, so nothing else in the stack notices.
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    assert schema.verify_against_tables(conn) == []

    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute(cast(LiteralString, mutation))

    problems = schema.verify_against_tables(conn)
    assert any(repr(column) in p and "orders" in p for p in problems), (
        f"expected drift on orders.{column}, got: {problems}"
    )


def test_verify_against_tables_detects_missing_index(
    clean_db: PostgresDatabaseSettings,
) -> None:
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    with conn.transaction(), conn.cursor() as cur:
        _ = cur.execute("DROP INDEX IF EXISTS orders_name_idx")
    problems = schema.verify_against_tables(conn)
    assert any("orders_name_idx" in p for p in problems)


def test_live_index_names_returns_declared_indexes(
    clean_db: PostgresDatabaseSettings,
) -> None:
    """Live smoke leg of the indisvalid coverage triangle.

    Verifies the _LIVE_VALID_INDEXES_QUERY is syntactically and semantically
    correct against the real catalog, regardless of test-role privileges.
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    live = schema.live_index_names(conn)
    declared = schema.declared_index_names()
    assert live >= declared


def test_verify_treats_invalid_index_as_missing(
    clean_db: PostgresDatabaseSettings,
) -> None:
    """Privileged leg of the indisvalid coverage triangle.

    Requires superuser (UPDATE pg_index permission). Skips if the test
    role lacks that permission. The other two legs in the triangle
    (unit mock + live smoke) run unconditionally and cover the consumer
    logic and reader query correctness independently.
    """
    conn = connection.connect(clean_db)
    migrations.apply_pending_migrations(conn)
    try:
        with conn.transaction(), conn.cursor() as cur:
            _ = cur.execute("UPDATE pg_index SET indisvalid = false WHERE indexrelid = 'orders_name_idx'::regclass")
    except psycopg.errors.InsufficientPrivilege:
        pytest.skip("requires superuser role to UPDATE pg_index")
    except Exception as exc:
        pytest.skip(f"pg_index UPDATE not permitted: {exc}")

    problems = schema.verify_against_tables(conn)
    assert any("orders_name_idx" in p for p in problems), f"Expected 'orders_name_idx' in drift report, got: {problems}"


def test_advisory_lock_serializes_concurrent_callers(
    clean_db: PostgresDatabaseSettings,
) -> None:
    """Second caller blocks until the first releases the advisory lock."""
    lock_acquired = threading.Event()
    ok_to_release = threading.Event()
    second_done = threading.Event()
    errors: list[Exception] = []

    def hold_lock() -> None:
        try:
            conn1 = _raw_connect(clean_db)
            with _advisory_lock(conn1):
                lock_acquired.set()
                ok_to_release.wait(timeout=8.0)
        except Exception as exc:
            errors.append(exc)

    def run_apply() -> None:
        try:
            lock_acquired.wait(timeout=5.0)
            conn2 = _raw_connect(clean_db)
            migrations.apply_pending_migrations(conn2)
        except Exception as exc:
            errors.append(exc)
        finally:
            second_done.set()

    t1 = threading.Thread(target=hold_lock, daemon=True)
    t2 = threading.Thread(target=run_apply, daemon=True)
    t1.start()
    lock_acquired.wait(timeout=5.0)
    t2.start()

    import time

    time.sleep(0.4)
    assert not second_done.is_set(), "apply_pending_migrations returned before the advisory lock was released"

    ok_to_release.set()
    t1.join(timeout=5.0)
    t2.join(timeout=8.0)

    assert not errors, f"Thread errors: {errors}"
