# Eleanor configuration file
# See: https://github.com/39alpha/eleanor

[output]
type = "postgres"                   # postgres | csv | null

[output.args.database]
host = "localhost"
port = 5432
database = "eleanor"
# username = "eleanor"
# password = "secret"
# sslmode = "prefer"

[parallel]
backend = "multiprocessing"         # serial | multiprocessing
chunks_per_worker = 10
