---
title: "Getting Started"
---

# Dependencies

> **NOTE**: We support both Linux and MacOS systems. You might have some luck using the Linux Subsystem for Windows, but
> we don't pretend to support it.

Eleanor requires `python>=3.11` an two external runtime dependencies:

1. A slightly modified version of EQ3/6 found at [39alpha/eq3_6](https://github.com/39alpha/eq3_6). Future versions will
likely add other kernels based on other speciation tools, but EQ3/6 is what we have now.
2. A [PostgreSQL](https://www.postgresql.org/) server. This is honestly the most odious dependency to install, but the PostgreSQL docs are pretty good.

There are two dev dependencies required for installation:

1. [`gfortran`](https://fortran-lang.org/learn/os_setup/install_gfortran/) - you should be able to install `gfortran`
with your system's package manager (e.g. homebrew)
2. [`meson`](https://mesonbuild.com/) - I recommend installing this via `uv`. See [Installation](#installation) below.

# Installation

I highly recommend using [`uv`](https://docs.astral.sh/uv/) to install eleanor:

```bash
uv tool install meson # If you haven't installed meson already
```

```bash
uv tool install git+https://github.com/39alpha/eleanor
```
